// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: corp.proto

package corp

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCorpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorpReq) Reset() {
	*x = GetCorpReq{}
	mi := &file_corp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorpReq) ProtoMessage() {}

func (x *GetCorpReq) ProtoReflect() protoreflect.Message {
	mi := &file_corp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorpReq.ProtoReflect.Descriptor instead.
func (*GetCorpReq) Descriptor() ([]byte, []int) {
	return file_corp_proto_rawDescGZIP(), []int{0}
}

type GetCorpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorpResp) Reset() {
	*x = GetCorpResp{}
	mi := &file_corp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorpResp) ProtoMessage() {}

func (x *GetCorpResp) ProtoReflect() protoreflect.Message {
	mi := &file_corp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorpResp.ProtoReflect.Descriptor instead.
func (*GetCorpResp) Descriptor() ([]byte, []int) {
	return file_corp_proto_rawDescGZIP(), []int{1}
}

var File_corp_proto protoreflect.FileDescriptor

const file_corp_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"corp.proto\x12\x04corp\x1a\x0fmgorm_ext.proto\x1a\x13easymicro_ext.proto\"\f\n" +
	"\n" +
	"GetCorpReq\"\r\n" +
	"\vGetCorpResp26\n" +
	"\x04Corp\x12.\n" +
	"\aGetCorp\x12\x10.corp.GetCorpReq\x1a\x11.corp.GetCorpRespB-Z+github.com/995933447/easymicro/example/corpb\x06proto3"

var (
	file_corp_proto_rawDescOnce sync.Once
	file_corp_proto_rawDescData []byte
)

func file_corp_proto_rawDescGZIP() []byte {
	file_corp_proto_rawDescOnce.Do(func() {
		file_corp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corp_proto_rawDesc), len(file_corp_proto_rawDesc)))
	})
	return file_corp_proto_rawDescData
}

var file_corp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_corp_proto_goTypes = []any{
	(*GetCorpReq)(nil),  // 0: corp.GetCorpReq
	(*GetCorpResp)(nil), // 1: corp.GetCorpResp
}
var file_corp_proto_depIdxs = []int32{
	0, // 0: corp.Corp.GetCorp:input_type -> corp.GetCorpReq
	1, // 1: corp.Corp.GetCorp:output_type -> corp.GetCorpResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_corp_proto_init() }
func file_corp_proto_init() {
	if File_corp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corp_proto_rawDesc), len(file_corp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_corp_proto_goTypes,
		DependencyIndexes: file_corp_proto_depIdxs,
		MessageInfos:      file_corp_proto_msgTypes,
	}.Build()
	File_corp_proto = out.File
	file_corp_proto_goTypes = nil
	file_corp_proto_depIdxs = nil
}
