// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: corp.proto

package corp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Corp_GetCorp_FullMethodName = "/corp.Corp/GetCorp"
)

// CorpClient is the client API for Corp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CorpClient interface {
	GetCorp(ctx context.Context, in *GetCorpReq, opts ...grpc.CallOption) (*GetCorpResp, error)
}

type corpClient struct {
	cc grpc.ClientConnInterface
}

func NewCorpClient(cc grpc.ClientConnInterface) CorpClient {
	return &corpClient{cc}
}

func (c *corpClient) GetCorp(ctx context.Context, in *GetCorpReq, opts ...grpc.CallOption) (*GetCorpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCorpResp)
	err := c.cc.Invoke(ctx, Corp_GetCorp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CorpServer is the server API for Corp service.
// All implementations must embed UnimplementedCorpServer
// for forward compatibility.
type CorpServer interface {
	GetCorp(context.Context, *GetCorpReq) (*GetCorpResp, error)
	mustEmbedUnimplementedCorpServer()
}

// UnimplementedCorpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCorpServer struct{}

func (UnimplementedCorpServer) GetCorp(context.Context, *GetCorpReq) (*GetCorpResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCorp not implemented")
}
func (UnimplementedCorpServer) mustEmbedUnimplementedCorpServer() {}
func (UnimplementedCorpServer) testEmbeddedByValue()              {}

// UnsafeCorpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CorpServer will
// result in compilation errors.
type UnsafeCorpServer interface {
	mustEmbedUnimplementedCorpServer()
}

func RegisterCorpServer(s grpc.ServiceRegistrar, srv CorpServer) {
	// If the following call pancis, it indicates UnimplementedCorpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Corp_ServiceDesc, srv)
}

func _Corp_GetCorp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorpServer).GetCorp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Corp_GetCorp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorpServer).GetCorp(ctx, req.(*GetCorpReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Corp_ServiceDesc is the grpc.ServiceDesc for Corp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Corp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corp.Corp",
	HandlerType: (*CorpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCorp",
			Handler:    _Corp_GetCorp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "corp.proto",
}
