// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package corp

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "easymicro"
	EasymicroDiscoveryName = "default"
)

const EasymicroGRPCPbServiceNameCorp = "corp.Corp"

var CorpDefault = &Corp{}

func CorpGRPC() *Corp {
	return CorpDefault
}

func NewCorpGRPC(dialOpts ...grpc.DialOption) *Corp {
	return &Corp{
		dialOpts: dialOpts,
	}
}

type Corp struct {
	c        CorpClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *Corp) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *Corp) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameCorp)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameCorp, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewCorpClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *Corp) GetCorp(ctx context.Context, in *GetCorpReq, opts ...grpc.CallOption) (*GetCorpResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetCorp(ctx, in, opts...)
}
