// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package jobpub

import (
	"context"

	"github.com/995933447/easymicro/example/echo"
	"github.com/995933447/easymicro/grpc/middleservice/job"
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
)

var PubEchoServiceProxyEchoJob func(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error

var PubEchoServiceProxyEchoAsyncJob func(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error

var BatchPubEchoServiceProxyEchoJob func(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error

var BatchPubEchoServiceProxyEchoAsyncJob func(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error
