// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package jobpub

import (
	"context"

	"github.com/995933447/easymicro/example/echo"
	"github.com/995933447/easymicro/grpc/middleservice/job"
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
)

var PubEchoServiceBasicEchoJob func(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error

var PubEchoServiceBasicEchoAsyncJob func(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error

var BatchPubEchoServiceBasicEchoJob func(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error

var BatchPubEchoServiceBasicEchoAsyncJob func(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error
