// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
	"github.com/995933447/easymicro/grpc/middleservice/jobschedserver/handler"
	"github.com/995933447/easymicro/nats"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "PubJob", handler.JobSchedHandler.PubJob, func() *jobsched.PubJobReq {
		return &jobsched.PubJobReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "SetJob", handler.JobSchedHandler.SetJob, func() *jobsched.SetJobReq {
		return &jobsched.SetJobReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "SetJobsByBizId", handler.JobSchedHandler.SetJobsByBizId, func() *jobsched.SetJobsByBizIdReq {
		return &jobsched.SetJobsByBizIdReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "StopJob", handler.JobSchedHandler.StopJob, func() *jobsched.StopJobReq {
		return &jobsched.StopJobReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "StopJobByUniqKey", handler.JobSchedHandler.StopJobByUniqKey, func() *jobsched.StopJobByUniqKeyReq {
		return &jobsched.StopJobByUniqKeyReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "StopJobsByBizId", handler.JobSchedHandler.StopJobsByBizId, func() *jobsched.StopJobsByBizIdReq {
		return &jobsched.StopJobsByBizIdReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "GetJob", handler.JobSchedHandler.GetJob, func() *jobsched.GetJobReq {
		return &jobsched.GetJobReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "GetJobsByBizId", handler.JobSchedHandler.GetJobsByBizId, func() *jobsched.GetJobsByBizIdReq {
		return &jobsched.GetJobsByBizIdReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "GetJobByUniqKey", handler.JobSchedHandler.GetJobByUniqKey, func() *jobsched.GetJobByUniqKeyReq {
		return &jobsched.GetJobByUniqKeyReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "HeartBeatAsyncJob", handler.JobSchedHandler.HeartBeatAsyncJob, func() *jobsched.HeartBeatAsyncJobReq {
		return &jobsched.HeartBeatAsyncJobReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "ClearExpiredJobs", handler.JobSchedHandler.ClearExpiredJobs, func() *jobsched.ClearExpiredJobsReq {
		return &jobsched.ClearExpiredJobsReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobsched.EasymicroGRPCPbServiceNameJobSched, "DeleteJob", handler.JobSchedHandler.DeleteJob, func() *jobsched.DeleteJobReq {
		return &jobsched.DeleteJobReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
