// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
	"github.com/995933447/easymicro/grpc/middleservice/jobschedserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	jobsched.EasymicroGRPCPbServiceNameJobSched,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	jobsched.RegisterJobSchedServer(server, handler.JobSchedHandler)
	return nil
}
