// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package jobpub

import (
	"context"

	"github.com/995933447/easymicro/grpc/middleservice/job"
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
)

var PubJobSchedServiceClearExpiredJobsJob func(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *jobsched.ClearExpiredJobsReq) error

var PubJobSchedServiceClearExpiredJobsAsyncJob func(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *jobsched.ClearExpiredJobsReq) error

var BatchPubJobSchedServiceClearExpiredJobsJob func(ctx context.Context, pubJobReq *job.BatchPubReq, arg *jobsched.ClearExpiredJobsReq) error

var BatchPubJobSchedServiceClearExpiredJobsAsyncJob func(ctx context.Context, pubJobReq *job.BatchPubReq, arg *jobsched.ClearExpiredJobsReq) error
