// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: enum.proto

package enum

import (
	_ "github.com/995933447/easymicro/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCPort int32

const (
	RPCPort_RPCPortNil  RPCPort = 0
	RPCPort_RPCPortUser RPCPort = 20011
)

// Enum value maps for RPCPort.
var (
	RPCPort_name = map[int32]string{
		0:     "RPCPortNil",
		20011: "RPCPortUser",
	}
	RPCPort_value = map[string]int32{
		"RPCPortNil":  0,
		"RPCPortUser": 20011,
	}
)

func (x RPCPort) Enum() *RPCPort {
	p := new(RPCPort)
	*p = x
	return p
}

func (x RPCPort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPCPort) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (RPCPort) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x RPCPort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPCPort.Descriptor instead.
func (RPCPort) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto\x12\x04enum\x1a\x13easymicro_ext.proto*2\n" +
	"\aRPCPort\x12\x0e\n" +
	"\n" +
	"RPCPortNil\x10\x00\x12\x11\n" +
	"\vRPCPortUser\x10\xab\x9c\x01\x1a\x04\x88\x9d \x01B-Z+github.com/995933447/easymicro/example/enumb\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_proto_goTypes = []any{
	(RPCPort)(0), // 0: enum.RPCPort
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
