// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: jobexec.proto

package jobexec

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil                  ErrCode = 0
	ErrCode_ErrCodeCallbackFuncNotFound ErrCode = 4001
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ErrCodeNil",
		4001: "ErrCodeCallbackFuncNotFound",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":                  0,
		"ErrCodeCallbackFuncNotFound": 4001,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_jobexec_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_jobexec_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_jobexec_proto_rawDescGZIP(), []int{0}
}

type ExecJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arg           string                 `protobuf:"bytes,1,opt,name=arg,proto3" json:"arg,omitempty"`                                       // 作业参数
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                      // 作业id
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`                // 作业名字
	JobGroup      string                 `protobuf:"bytes,4,opt,name=job_group,json=jobGroup,proto3" json:"job_group,omitempty"`             // 作业分组
	BizId         string                 `protobuf:"bytes,5,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`                      // 作业业务id
	Attempted     uint32                 `protobuf:"varint,6,opt,name=attempted,proto3" json:"attempted,omitempty"`                          // 已运行次数
	Mode          int32                  `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`                                    // 模式，执行模式.1.指定时间戳（只运行一次）,2.cron表达式（持续间隔触发） 3.间隔执行（持续间隔出发）
	MaxRunSec     uint32                 `protobuf:"varint,8,opt,name=max_run_sec,json=maxRunSec,proto3" json:"max_run_sec,omitempty"`       // 最长运行时间
	PlanSchedAt   int64                  `protobuf:"varint,9,opt,name=plan_sched_at,json=planSchedAt,proto3" json:"plan_sched_at,omitempty"` // 计划触发时间，实际触发时间与计划可能因为并发控制原因导致有些许误差
	RpcSrv        string                 `protobuf:"bytes,10,opt,name=rpc_srv,json=rpcSrv,proto3" json:"rpc_srv,omitempty"`
	RpcMethod     string                 `protobuf:"bytes,11,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpc_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecJobReq) Reset() {
	*x = ExecJobReq{}
	mi := &file_jobexec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecJobReq) ProtoMessage() {}

func (x *ExecJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobexec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecJobReq.ProtoReflect.Descriptor instead.
func (*ExecJobReq) Descriptor() ([]byte, []int) {
	return file_jobexec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecJobReq) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *ExecJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecJobReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ExecJobReq) GetJobGroup() string {
	if x != nil {
		return x.JobGroup
	}
	return ""
}

func (x *ExecJobReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *ExecJobReq) GetAttempted() uint32 {
	if x != nil {
		return x.Attempted
	}
	return 0
}

func (x *ExecJobReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ExecJobReq) GetMaxRunSec() uint32 {
	if x != nil {
		return x.MaxRunSec
	}
	return 0
}

func (x *ExecJobReq) GetPlanSchedAt() int64 {
	if x != nil {
		return x.PlanSchedAt
	}
	return 0
}

func (x *ExecJobReq) GetRpcSrv() string {
	if x != nil {
		return x.RpcSrv
	}
	return ""
}

func (x *ExecJobReq) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

type ExecJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extra         string                 `protobuf:"bytes,1,opt,name=extra,proto3" json:"extra,omitempty"`                                        // 结果额外信息，将保存
	IsRunInAsync  bool                   `protobuf:"varint,2,opt,name=is_run_in_async,json=isRunInAsync,proto3" json:"is_run_in_async,omitempty"` // 是否异步运行，异步运行调度器将不等待结果，采用心跳检查结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecJobResp) Reset() {
	*x = ExecJobResp{}
	mi := &file_jobexec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecJobResp) ProtoMessage() {}

func (x *ExecJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobexec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecJobResp.ProtoReflect.Descriptor instead.
func (*ExecJobResp) Descriptor() ([]byte, []int) {
	return file_jobexec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecJobResp) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *ExecJobResp) GetIsRunInAsync() bool {
	if x != nil {
		return x.IsRunInAsync
	}
	return false
}

var File_jobexec_proto protoreflect.FileDescriptor

const file_jobexec_proto_rawDesc = "" +
	"\n" +
	"\rjobexec.proto\x12\ajobexec\x1a\x0fmgorm_ext.proto\x1a\x13easymicro_ext.proto\"\xb2\x02\n" +
	"\n" +
	"ExecJobReq\x12\x10\n" +
	"\x03arg\x18\x01 \x01(\tR\x03arg\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x1b\n" +
	"\tjob_group\x18\x04 \x01(\tR\bjobGroup\x12\x15\n" +
	"\x06biz_id\x18\x05 \x01(\tR\x05bizId\x12\x1c\n" +
	"\tattempted\x18\x06 \x01(\rR\tattempted\x12\x12\n" +
	"\x04mode\x18\a \x01(\x05R\x04mode\x12\x1e\n" +
	"\vmax_run_sec\x18\b \x01(\rR\tmaxRunSec\x12\"\n" +
	"\rplan_sched_at\x18\t \x01(\x03R\vplanSchedAt\x12\x17\n" +
	"\arpc_srv\x18\n" +
	" \x01(\tR\x06rpcSrv\x12\x1d\n" +
	"\n" +
	"rpc_method\x18\v \x01(\tR\trpcMethod\"J\n" +
	"\vExecJobResp\x12\x14\n" +
	"\x05extra\x18\x01 \x01(\tR\x05extra\x12%\n" +
	"\x0fis_run_in_async\x18\x02 \x01(\bR\fisRunInAsync*;\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12 \n" +
	"\x1bErrCodeCallbackFuncNotFound\x10\xa1\x1f2?\n" +
	"\aJobExec\x124\n" +
	"\aExecJob\x12\x13.jobexec.ExecJobReq\x1a\x14.jobexec.ExecJobRespB;Z9github.com/995933447/easymicro/grpc/middleservice/jobexecb\x06proto3"

var (
	file_jobexec_proto_rawDescOnce sync.Once
	file_jobexec_proto_rawDescData []byte
)

func file_jobexec_proto_rawDescGZIP() []byte {
	file_jobexec_proto_rawDescOnce.Do(func() {
		file_jobexec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobexec_proto_rawDesc), len(file_jobexec_proto_rawDesc)))
	})
	return file_jobexec_proto_rawDescData
}

var file_jobexec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobexec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jobexec_proto_goTypes = []any{
	(ErrCode)(0),        // 0: jobexec.ErrCode
	(*ExecJobReq)(nil),  // 1: jobexec.ExecJobReq
	(*ExecJobResp)(nil), // 2: jobexec.ExecJobResp
}
var file_jobexec_proto_depIdxs = []int32{
	1, // 0: jobexec.JobExec.ExecJob:input_type -> jobexec.ExecJobReq
	2, // 1: jobexec.JobExec.ExecJob:output_type -> jobexec.ExecJobResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobexec_proto_init() }
func file_jobexec_proto_init() {
	if File_jobexec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobexec_proto_rawDesc), len(file_jobexec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobexec_proto_goTypes,
		DependencyIndexes: file_jobexec_proto_depIdxs,
		EnumInfos:         file_jobexec_proto_enumTypes,
		MessageInfos:      file_jobexec_proto_msgTypes,
	}.Build()
	File_jobexec_proto = out.File
	file_jobexec_proto_goTypes = nil
	file_jobexec_proto_depIdxs = nil
}
