// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package jobexec

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "easymicro"
	EasymicroDiscoveryName = "default"
)

const EasymicroGRPCPbServiceNameJobExec = "jobexec.JobExec"

var JobExecDefault = &JobExec{}

func JobExecGRPC() *JobExec {
	return JobExecDefault
}

func NewJobExecGRPC(dialOpts ...grpc.DialOption) *JobExec {
	return &JobExec{
		dialOpts: dialOpts,
	}
}

type JobExec struct {
	c        JobExecClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *JobExec) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *JobExec) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameJobExec)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameJobExec, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewJobExecClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *JobExec) ExecJob(ctx context.Context, in *ExecJobReq, opts ...grpc.CallOption) (*ExecJobResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ExecJob(ctx, in, opts...)
}
