// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package healthchecker

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = ""
	EasymicroDiscoveryName = ""
)

const EasymicroGRPCPbServiceNameHealthChecker = "healthchecker.HealthChecker"

var HealthCheckerDefault = &HealthChecker{}

func HealthCheckerGRPC() *HealthChecker {
	return HealthCheckerDefault
}

func NewHealthCheckerGRPC(dialOpts ...grpc.DialOption) *HealthChecker {
	return &HealthChecker{
		dialOpts: dialOpts,
	}
}

type HealthChecker struct {
	c        HealthCheckerClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *HealthChecker) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *HealthChecker) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameHealthChecker)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameHealthChecker, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewHealthCheckerClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}
