// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package impl

import (
	"context"

	"github.com/995933447/easymicro/example/echo"
	"github.com/995933447/easymicro/example/echoserver/handler"
	"github.com/995933447/easymicro/example/echoserver/jobpub"
	"github.com/995933447/easymicro/grpc/middleservice/job"
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
)

func init() {
	jobpub.PubEchoServiceBasicEchoJob = PubEchoServiceBasicEchoJob
	jobpub.PubEchoServiceBasicEchoAsyncJob = PubEchoServiceBasicEchoAsyncJob
	jobpub.BatchPubEchoServiceBasicEchoJob = BatchPubEchoServiceBasicEchoJob
	jobpub.BatchPubEchoServiceBasicEchoAsyncJob = BatchPubEchoServiceBasicEchoAsyncJob
}

func PubEchoServiceBasicEchoJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error {
	return pubEchoServiceBasicEchoJob(ctx, pubJobReq, arg, false)
}

func PubEchoServiceBasicEchoAsyncJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error {
	return pubEchoServiceBasicEchoJob(ctx, pubJobReq, arg, true)
}

func pubEchoServiceBasicEchoJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq, isRunInAsync bool) error {
	pubJobReq.RpcSrv = echo.EasymicroGRPCPbServiceNameEcho
	pubJobReq.RpcMethod = "BasicEcho"

	_, err := job.Pub(ctx, pubJobReq, arg, handler.EchoHandler.BasicEcho, isRunInAsync)
	if err != nil {
		return err
	}
	return nil
}

func BatchPubEchoServiceBasicEchoJob(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error {
	return job.BatchPubSameRPC(ctx, echo.EasymicroGRPCPbServiceNameEcho, "BasicEcho", pubJobReq, handler.EchoHandler.BasicEcho, false)
}

func BatchPubEchoServiceBasicEchoAsyncJob(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error {
	return job.BatchPubSameRPC(ctx, echo.EasymicroGRPCPbServiceNameEcho, "BasicEcho", pubJobReq, handler.EchoHandler.BasicEcho, true)
}
