// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package impl

import (
	"context"

	"github.com/995933447/easymicro/example/echo"
	"github.com/995933447/easymicro/example/echoserver/handler"
	"github.com/995933447/easymicro/example/echoserver/jobpub"
	"github.com/995933447/easymicro/grpc/middleservice/job"
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
)

func init() {
	jobpub.PubEchoServiceProxyEchoJob = PubEchoServiceProxyEchoJob
	jobpub.PubEchoServiceProxyEchoAsyncJob = PubEchoServiceProxyEchoAsyncJob
	jobpub.BatchPubEchoServiceProxyEchoJob = BatchPubEchoServiceProxyEchoJob
	jobpub.BatchPubEchoServiceProxyEchoAsyncJob = BatchPubEchoServiceProxyEchoAsyncJob
}

func PubEchoServiceProxyEchoJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error {
	return pubEchoServiceProxyEchoJob(ctx, pubJobReq, arg, false)
}

func PubEchoServiceProxyEchoAsyncJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq) error {
	return pubEchoServiceProxyEchoJob(ctx, pubJobReq, arg, true)
}

func pubEchoServiceProxyEchoJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *echo.EchoReq, isRunInAsync bool) error {
	pubJobReq.RpcSrv = echo.EasymicroGRPCPbServiceNameEcho
	pubJobReq.RpcMethod = "ProxyEcho"

	_, err := job.Pub(ctx, pubJobReq, arg, handler.EchoHandler.ProxyEcho, isRunInAsync)
	if err != nil {
		return err
	}
	return nil
}

func BatchPubEchoServiceProxyEchoJob(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error {
	return job.BatchPubSameRPC(ctx, echo.EasymicroGRPCPbServiceNameEcho, "ProxyEcho", pubJobReq, handler.EchoHandler.ProxyEcho, false)
}

func BatchPubEchoServiceProxyEchoAsyncJob(ctx context.Context, pubJobReq *job.BatchPubReq, arg *echo.EchoReq) error {
	return job.BatchPubSameRPC(ctx, echo.EasymicroGRPCPbServiceNameEcho, "ProxyEcho", pubJobReq, handler.EchoHandler.ProxyEcho, true)
}
