// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/example/user"
	"github.com/995933447/easymicro/example/usersrv/handler"
	"github.com/995933447/easymicro/nats"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(user.EasymicroGRPCPbServiceNameUser, "GetUserInfo", handler.UserHandler.GetUserInfo, func() *user.GetUserInfoReq {
		return &user.GetUserInfoReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(user.EasymicroGRPCPbServiceNameUser, "ProxyEcho", handler.UserHandler.ProxyEcho, func() *user.GetUserInfoReq {
		return &user.GetUserInfoReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
