// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package impl

import (
	"context"

	"github.com/995933447/easymicro/grpc/middleservice/job"
	"github.com/995933447/easymicro/grpc/middleservice/jobsched"
	"github.com/995933447/easymicro/grpc/middleservice/jobschedserver/handler"
	"github.com/995933447/easymicro/grpc/middleservice/jobschedserver/jobpub"
)

func init() {
	jobpub.PubJobSchedServiceClearExpiredJobsJob = PubJobSchedServiceClearExpiredJobsJob
	jobpub.PubJobSchedServiceClearExpiredJobsAsyncJob = PubJobSchedServiceClearExpiredJobsAsyncJob
	jobpub.BatchPubJobSchedServiceClearExpiredJobsJob = BatchPubJobSchedServiceClearExpiredJobsJob
	jobpub.BatchPubJobSchedServiceClearExpiredJobsAsyncJob = BatchPubJobSchedServiceClearExpiredJobsAsyncJob
}

func PubJobSchedServiceClearExpiredJobsJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *jobsched.ClearExpiredJobsReq) error {
	return pubJobSchedServiceClearExpiredJobsJob(ctx, pubJobReq, arg, false)
}

func PubJobSchedServiceClearExpiredJobsAsyncJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *jobsched.ClearExpiredJobsReq) error {
	return pubJobSchedServiceClearExpiredJobsJob(ctx, pubJobReq, arg, true)
}

func pubJobSchedServiceClearExpiredJobsJob(ctx context.Context, pubJobReq *jobsched.PubJobReq, arg *jobsched.ClearExpiredJobsReq, isRunInAsync bool) error {
	pubJobReq.RpcSrv = jobsched.EasymicroGRPCPbServiceNameJobSched
	pubJobReq.RpcMethod = "ClearExpiredJobs"

	_, err := job.Pub(ctx, pubJobReq, arg, handler.JobSchedHandler.ClearExpiredJobs, isRunInAsync)
	if err != nil {
		return err
	}
	return nil
}

func BatchPubJobSchedServiceClearExpiredJobsJob(ctx context.Context, pubJobReq *job.BatchPubReq, arg *jobsched.ClearExpiredJobsReq) error {
	return job.BatchPubSameRPC(ctx, jobsched.EasymicroGRPCPbServiceNameJobSched, "ClearExpiredJobs", pubJobReq, handler.JobSchedHandler.ClearExpiredJobs, false)
}

func BatchPubJobSchedServiceClearExpiredJobsAsyncJob(ctx context.Context, pubJobReq *job.BatchPubReq, arg *jobsched.ClearExpiredJobsReq) error {
	return job.BatchPubSameRPC(ctx, jobsched.EasymicroGRPCPbServiceNameJobSched, "ClearExpiredJobs", pubJobReq, handler.JobSchedHandler.ClearExpiredJobs, true)
}
