// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/grpc/middleservice/healthchecker"
	"github.com/995933447/easymicro/grpc/middleservice/healthcheckerserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	healthchecker.EasymicroGRPCPbServiceNameHealthChecker,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	healthchecker.RegisterHealthCheckerServer(server, handler.HealthCheckerHandler)
	return nil
}
