// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: healthreporter.proto

package healthreporter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PingService   string                 `protobuf:"bytes,1,opt,name=ping_service,json=pingService,proto3" json:"ping_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_healthreporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_healthreporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_healthreporter_proto_rawDescGZIP(), []int{0}
}

func (x *PingReq) GetPingService() string {
	if x != nil {
		return x.PingService
	}
	return ""
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_healthreporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_healthreporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_healthreporter_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_healthreporter_proto protoreflect.FileDescriptor

const file_healthreporter_proto_rawDesc = "" +
	"\n" +
	"\x14healthreporter.proto\x12\x0ehealthreporter\",\n" +
	"\aPingReq\x12!\n" +
	"\fping_service\x18\x01 \x01(\tR\vpingService\"\x1a\n" +
	"\bPingResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2M\n" +
	"\x0eHealthReporter\x12;\n" +
	"\x04Ping\x12\x17.healthreporter.PingReq\x1a\x18.healthreporter.PingResp\"\x00BBZ@github.com/995933447/easymicro/grpc/middleservice/healthreporterb\x06proto3"

var (
	file_healthreporter_proto_rawDescOnce sync.Once
	file_healthreporter_proto_rawDescData []byte
)

func file_healthreporter_proto_rawDescGZIP() []byte {
	file_healthreporter_proto_rawDescOnce.Do(func() {
		file_healthreporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_healthreporter_proto_rawDesc), len(file_healthreporter_proto_rawDesc)))
	})
	return file_healthreporter_proto_rawDescData
}

var file_healthreporter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_healthreporter_proto_goTypes = []any{
	(*PingReq)(nil),  // 0: healthreporter.PingReq
	(*PingResp)(nil), // 1: healthreporter.PingResp
}
var file_healthreporter_proto_depIdxs = []int32{
	0, // 0: healthreporter.HealthReporter.Ping:input_type -> healthreporter.PingReq
	1, // 1: healthreporter.HealthReporter.Ping:output_type -> healthreporter.PingResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_healthreporter_proto_init() }
func file_healthreporter_proto_init() {
	if File_healthreporter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_healthreporter_proto_rawDesc), len(file_healthreporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthreporter_proto_goTypes,
		DependencyIndexes: file_healthreporter_proto_depIdxs,
		MessageInfos:      file_healthreporter_proto_msgTypes,
	}.Build()
	File_healthreporter_proto = out.File
	file_healthreporter_proto_goTypes = nil
	file_healthreporter_proto_depIdxs = nil
}
