// Code generated by protoc-gen-grpc-client. DO NOT EDIT.
package user

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const EasymicroGRPCSchema = ""

const EasymicroPbServiceNameUser = "user.User"

var UserDefault = &User{}

func UserRPC() *User {
	return UserDefault
}

func NewUserRPC(dialOpts ...grpc.DialOption) *User {
	return &User{
		dialOpts: dialOpts,
	}
}

type User struct {
	c        UserClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *User) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *User) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroPbServiceNameUser)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroPbServiceNameUser, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewUserClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *User) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetUserInfo(ctx, in, opts...)
}

func (s *User) ProxyEcho(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ProxyEcho(ctx, in, opts...)
}
