// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/example/user"
	"github.com/995933447/easymicro/example/userserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	user.EasymicroGRPCPbServiceNameUser,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	user.RegisterUserServer(server, handler.UserHandler)
	return nil
}
