package main

const jsonSchemaOutputGoFilTemplate = `// Code generated by protoc-gen-easymicro-jsonschema. DO NOT EDIT.
package main

import (
	"fmt"
	"log"

	"{{.ServiceClientImportPath}}"
	"github.com/995933447/runtimeutil"
	"github.com/invopop/jsonschema"
	jsoniter "github.com/json-iterator/go"
)

func main() {
	schema := Output()
	s, err := jsoniter.MarshalToString(schema)
	if err != nil {
		log.Fatal(runtimeutil.NewStackErr(err))
	}
	fmt.Print(s)
}

func OutputFormatJsonString() (string, error) {
	b, err := OutputFormatJson()
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func OutputFormatJson() ([]byte, error) {
	schema := Output()
	return jsoniter.Marshal(schema)
}

func Output() *jsonschema.Schema {
	r := &jsonschema.Reflector{}
	r.DoNotReference = {{ .DoNotReference }}
	r.AllowAdditionalProperties = {{ .AllowAdditionalProperties }}
	r.RequiredFromJSONSchemaTags = {{ .RequiredFromJSONSchemaTags }}
	r.FieldNameTag = "{{ .FieldNameTag }}"
	return r.Reflect(&{{ PathBase .ServiceClientImportPath }}.{{ .MessageName }}{{ if .IsORM }}Orm{{ .end }}{})
}
`
