// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/example/echo"
	"github.com/995933447/easymicro/example/echoserver/handler"
	"github.com/995933447/easymicro/nats"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"

	"github.com/995933447/easymicro/grpc/middleservice/job"
	"github.com/995933447/easymicro/grpc/middleservice/jobexec"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(echo.EasymicroGRPCPbServiceNameEcho, "BasicEcho", handler.EchoHandler.BasicEcho, func() *echo.EchoReq {
		return &echo.EchoReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(echo.EasymicroGRPCPbServiceNameEcho, "ProxyEcho", handler.EchoHandler.ProxyEcho, func() *echo.EchoReq {
		return &echo.EchoReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(jobexec.EasymicroGRPCPbServiceNameJobExec, "ExecJob", (&job.JobExecutor{}).ExecJob, func() *jobexec.ExecJobReq {
		return &jobexec.ExecJobReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
