// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/example/echo"
	"github.com/995933447/easymicro/example/echoserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	echo.EasymicroGRPCPbServiceNameEcho,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	echo.RegisterEchoServer(server, handler.EchoHandler)
	return nil
}
