// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package jobsched

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "easymicrojob"
	EasymicroDiscoveryName = "easymicrojob"
)

const EasymicroGRPCPbServiceNameJobSched = "jobsched.JobSched"

var JobSchedDefault = &JobSched{}

func JobSchedGRPC() *JobSched {
	return JobSchedDefault
}

func NewJobSchedGRPC(dialOpts ...grpc.DialOption) *JobSched {
	return &JobSched{
		dialOpts: dialOpts,
	}
}

type JobSched struct {
	c        JobSchedClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *JobSched) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *JobSched) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameJobSched)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameJobSched, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewJobSchedClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *JobSched) PubJob(ctx context.Context, in *PubJobReq, opts ...grpc.CallOption) (*PubJobResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.PubJob(ctx, in, opts...)
}

func (s *JobSched) SetJob(ctx context.Context, in *SetJobReq, opts ...grpc.CallOption) (*SetJobResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetJob(ctx, in, opts...)
}

func (s *JobSched) SetJobsByBizId(ctx context.Context, in *SetJobsByBizIdReq, opts ...grpc.CallOption) (*SetJobsByBizIdResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetJobsByBizId(ctx, in, opts...)
}

func (s *JobSched) StopJob(ctx context.Context, in *StopJobReq, opts ...grpc.CallOption) (*StopJobResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.StopJob(ctx, in, opts...)
}

func (s *JobSched) StopJobByUniqKey(ctx context.Context, in *StopJobByUniqKeyReq, opts ...grpc.CallOption) (*StopJobByUniqKeyResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.StopJobByUniqKey(ctx, in, opts...)
}

func (s *JobSched) StopJobsByBizId(ctx context.Context, in *StopJobsByBizIdReq, opts ...grpc.CallOption) (*StopJobsByBizIdResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.StopJobsByBizId(ctx, in, opts...)
}

func (s *JobSched) GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*GetJobResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetJob(ctx, in, opts...)
}

func (s *JobSched) GetJobsByBizId(ctx context.Context, in *GetJobsByBizIdReq, opts ...grpc.CallOption) (*GetJobsByBizIdResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetJobsByBizId(ctx, in, opts...)
}

func (s *JobSched) GetJobByUniqKey(ctx context.Context, in *GetJobByUniqKeyReq, opts ...grpc.CallOption) (*GetJobByUniqKeyResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetJobByUniqKey(ctx, in, opts...)
}

func (s *JobSched) HeartBeatAsyncJob(ctx context.Context, in *HeartBeatAsyncJobReq, opts ...grpc.CallOption) (*HeartBeatAsyncJobResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.HeartBeatAsyncJob(ctx, in, opts...)
}

func (s *JobSched) ClearExpiredJobs(ctx context.Context, in *ClearExpiredJobsReq, opts ...grpc.CallOption) (*ClearExpiredJobsResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ClearExpiredJobs(ctx, in, opts...)
}

func (s *JobSched) DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DeleteJob(ctx, in, opts...)
}
