// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: jobsched.proto

package jobsched

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobSched_PubJob_FullMethodName            = "/jobsched.JobSched/PubJob"
	JobSched_SetJob_FullMethodName            = "/jobsched.JobSched/SetJob"
	JobSched_SetJobsByBizId_FullMethodName    = "/jobsched.JobSched/SetJobsByBizId"
	JobSched_StopJob_FullMethodName           = "/jobsched.JobSched/StopJob"
	JobSched_StopJobByUniqKey_FullMethodName  = "/jobsched.JobSched/StopJobByUniqKey"
	JobSched_StopJobsByBizId_FullMethodName   = "/jobsched.JobSched/StopJobsByBizId"
	JobSched_GetJob_FullMethodName            = "/jobsched.JobSched/GetJob"
	JobSched_GetJobsByBizId_FullMethodName    = "/jobsched.JobSched/GetJobsByBizId"
	JobSched_GetJobByUniqKey_FullMethodName   = "/jobsched.JobSched/GetJobByUniqKey"
	JobSched_HeartBeatAsyncJob_FullMethodName = "/jobsched.JobSched/HeartBeatAsyncJob"
	JobSched_ClearExpiredJobs_FullMethodName  = "/jobsched.JobSched/ClearExpiredJobs"
	JobSched_DeleteJob_FullMethodName         = "/jobsched.JobSched/DeleteJob"
)

// JobSchedClient is the client API for JobSched service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobSchedClient interface {
	// 发布作业
	PubJob(ctx context.Context, in *PubJobReq, opts ...grpc.CallOption) (*PubJobResp, error)
	// 设置作业
	SetJob(ctx context.Context, in *SetJobReq, opts ...grpc.CallOption) (*SetJobResp, error)
	// 通过业务id设置作业
	SetJobsByBizId(ctx context.Context, in *SetJobsByBizIdReq, opts ...grpc.CallOption) (*SetJobsByBizIdResp, error)
	// 停止作业
	StopJob(ctx context.Context, in *StopJobReq, opts ...grpc.CallOption) (*StopJobResp, error)
	// 通过自定义唯一id停止作业
	StopJobByUniqKey(ctx context.Context, in *StopJobByUniqKeyReq, opts ...grpc.CallOption) (*StopJobByUniqKeyResp, error)
	// 通过业务id停止作业
	StopJobsByBizId(ctx context.Context, in *StopJobsByBizIdReq, opts ...grpc.CallOption) (*StopJobsByBizIdResp, error)
	// 查询作业
	GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*GetJobResp, error)
	// 根据业务id查询作业
	GetJobsByBizId(ctx context.Context, in *GetJobsByBizIdReq, opts ...grpc.CallOption) (*GetJobsByBizIdResp, error)
	// 根据唯一业务id查询作业
	GetJobByUniqKey(ctx context.Context, in *GetJobByUniqKeyReq, opts ...grpc.CallOption) (*GetJobByUniqKeyResp, error)
	// 异步作业心跳检查
	HeartBeatAsyncJob(ctx context.Context, in *HeartBeatAsyncJobReq, opts ...grpc.CallOption) (*HeartBeatAsyncJobResp, error)
	// 清理过期作业
	ClearExpiredJobs(ctx context.Context, in *ClearExpiredJobsReq, opts ...grpc.CallOption) (*ClearExpiredJobsResp, error)
	// 删除作业
	DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobResp, error)
}

type jobSchedClient struct {
	cc grpc.ClientConnInterface
}

func NewJobSchedClient(cc grpc.ClientConnInterface) JobSchedClient {
	return &jobSchedClient{cc}
}

func (c *jobSchedClient) PubJob(ctx context.Context, in *PubJobReq, opts ...grpc.CallOption) (*PubJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PubJobResp)
	err := c.cc.Invoke(ctx, JobSched_PubJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) SetJob(ctx context.Context, in *SetJobReq, opts ...grpc.CallOption) (*SetJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetJobResp)
	err := c.cc.Invoke(ctx, JobSched_SetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) SetJobsByBizId(ctx context.Context, in *SetJobsByBizIdReq, opts ...grpc.CallOption) (*SetJobsByBizIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetJobsByBizIdResp)
	err := c.cc.Invoke(ctx, JobSched_SetJobsByBizId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) StopJob(ctx context.Context, in *StopJobReq, opts ...grpc.CallOption) (*StopJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopJobResp)
	err := c.cc.Invoke(ctx, JobSched_StopJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) StopJobByUniqKey(ctx context.Context, in *StopJobByUniqKeyReq, opts ...grpc.CallOption) (*StopJobByUniqKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopJobByUniqKeyResp)
	err := c.cc.Invoke(ctx, JobSched_StopJobByUniqKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) StopJobsByBizId(ctx context.Context, in *StopJobsByBizIdReq, opts ...grpc.CallOption) (*StopJobsByBizIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopJobsByBizIdResp)
	err := c.cc.Invoke(ctx, JobSched_StopJobsByBizId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*GetJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResp)
	err := c.cc.Invoke(ctx, JobSched_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) GetJobsByBizId(ctx context.Context, in *GetJobsByBizIdReq, opts ...grpc.CallOption) (*GetJobsByBizIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobsByBizIdResp)
	err := c.cc.Invoke(ctx, JobSched_GetJobsByBizId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) GetJobByUniqKey(ctx context.Context, in *GetJobByUniqKeyReq, opts ...grpc.CallOption) (*GetJobByUniqKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobByUniqKeyResp)
	err := c.cc.Invoke(ctx, JobSched_GetJobByUniqKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) HeartBeatAsyncJob(ctx context.Context, in *HeartBeatAsyncJobReq, opts ...grpc.CallOption) (*HeartBeatAsyncJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartBeatAsyncJobResp)
	err := c.cc.Invoke(ctx, JobSched_HeartBeatAsyncJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) ClearExpiredJobs(ctx context.Context, in *ClearExpiredJobsReq, opts ...grpc.CallOption) (*ClearExpiredJobsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearExpiredJobsResp)
	err := c.cc.Invoke(ctx, JobSched_ClearExpiredJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedClient) DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobResp)
	err := c.cc.Invoke(ctx, JobSched_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobSchedServer is the server API for JobSched service.
// All implementations must embed UnimplementedJobSchedServer
// for forward compatibility.
type JobSchedServer interface {
	// 发布作业
	PubJob(context.Context, *PubJobReq) (*PubJobResp, error)
	// 设置作业
	SetJob(context.Context, *SetJobReq) (*SetJobResp, error)
	// 通过业务id设置作业
	SetJobsByBizId(context.Context, *SetJobsByBizIdReq) (*SetJobsByBizIdResp, error)
	// 停止作业
	StopJob(context.Context, *StopJobReq) (*StopJobResp, error)
	// 通过自定义唯一id停止作业
	StopJobByUniqKey(context.Context, *StopJobByUniqKeyReq) (*StopJobByUniqKeyResp, error)
	// 通过业务id停止作业
	StopJobsByBizId(context.Context, *StopJobsByBizIdReq) (*StopJobsByBizIdResp, error)
	// 查询作业
	GetJob(context.Context, *GetJobReq) (*GetJobResp, error)
	// 根据业务id查询作业
	GetJobsByBizId(context.Context, *GetJobsByBizIdReq) (*GetJobsByBizIdResp, error)
	// 根据唯一业务id查询作业
	GetJobByUniqKey(context.Context, *GetJobByUniqKeyReq) (*GetJobByUniqKeyResp, error)
	// 异步作业心跳检查
	HeartBeatAsyncJob(context.Context, *HeartBeatAsyncJobReq) (*HeartBeatAsyncJobResp, error)
	// 清理过期作业
	ClearExpiredJobs(context.Context, *ClearExpiredJobsReq) (*ClearExpiredJobsResp, error)
	// 删除作业
	DeleteJob(context.Context, *DeleteJobReq) (*DeleteJobResp, error)
	mustEmbedUnimplementedJobSchedServer()
}

// UnimplementedJobSchedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobSchedServer struct{}

func (UnimplementedJobSchedServer) PubJob(context.Context, *PubJobReq) (*PubJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PubJob not implemented")
}
func (UnimplementedJobSchedServer) SetJob(context.Context, *SetJobReq) (*SetJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetJob not implemented")
}
func (UnimplementedJobSchedServer) SetJobsByBizId(context.Context, *SetJobsByBizIdReq) (*SetJobsByBizIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetJobsByBizId not implemented")
}
func (UnimplementedJobSchedServer) StopJob(context.Context, *StopJobReq) (*StopJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJob not implemented")
}
func (UnimplementedJobSchedServer) StopJobByUniqKey(context.Context, *StopJobByUniqKeyReq) (*StopJobByUniqKeyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJobByUniqKey not implemented")
}
func (UnimplementedJobSchedServer) StopJobsByBizId(context.Context, *StopJobsByBizIdReq) (*StopJobsByBizIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJobsByBizId not implemented")
}
func (UnimplementedJobSchedServer) GetJob(context.Context, *GetJobReq) (*GetJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobSchedServer) GetJobsByBizId(context.Context, *GetJobsByBizIdReq) (*GetJobsByBizIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobsByBizId not implemented")
}
func (UnimplementedJobSchedServer) GetJobByUniqKey(context.Context, *GetJobByUniqKeyReq) (*GetJobByUniqKeyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobByUniqKey not implemented")
}
func (UnimplementedJobSchedServer) HeartBeatAsyncJob(context.Context, *HeartBeatAsyncJobReq) (*HeartBeatAsyncJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeatAsyncJob not implemented")
}
func (UnimplementedJobSchedServer) ClearExpiredJobs(context.Context, *ClearExpiredJobsReq) (*ClearExpiredJobsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearExpiredJobs not implemented")
}
func (UnimplementedJobSchedServer) DeleteJob(context.Context, *DeleteJobReq) (*DeleteJobResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedJobSchedServer) mustEmbedUnimplementedJobSchedServer() {}
func (UnimplementedJobSchedServer) testEmbeddedByValue()                  {}

// UnsafeJobSchedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobSchedServer will
// result in compilation errors.
type UnsafeJobSchedServer interface {
	mustEmbedUnimplementedJobSchedServer()
}

func RegisterJobSchedServer(s grpc.ServiceRegistrar, srv JobSchedServer) {
	// If the following call pancis, it indicates UnimplementedJobSchedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobSched_ServiceDesc, srv)
}

func _JobSched_PubJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).PubJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_PubJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).PubJob(ctx, req.(*PubJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_SetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).SetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_SetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).SetJob(ctx, req.(*SetJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_SetJobsByBizId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetJobsByBizIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).SetJobsByBizId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_SetJobsByBizId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).SetJobsByBizId(ctx, req.(*SetJobsByBizIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_StopJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).StopJob(ctx, req.(*StopJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_StopJobByUniqKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobByUniqKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).StopJobByUniqKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_StopJobByUniqKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).StopJobByUniqKey(ctx, req.(*StopJobByUniqKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_StopJobsByBizId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobsByBizIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).StopJobsByBizId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_StopJobsByBizId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).StopJobsByBizId(ctx, req.(*StopJobsByBizIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).GetJob(ctx, req.(*GetJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_GetJobsByBizId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsByBizIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).GetJobsByBizId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_GetJobsByBizId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).GetJobsByBizId(ctx, req.(*GetJobsByBizIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_GetJobByUniqKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobByUniqKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).GetJobByUniqKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_GetJobByUniqKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).GetJobByUniqKey(ctx, req.(*GetJobByUniqKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_HeartBeatAsyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatAsyncJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).HeartBeatAsyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_HeartBeatAsyncJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).HeartBeatAsyncJob(ctx, req.(*HeartBeatAsyncJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_ClearExpiredJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearExpiredJobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).ClearExpiredJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_ClearExpiredJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).ClearExpiredJobs(ctx, req.(*ClearExpiredJobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSched_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSched_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedServer).DeleteJob(ctx, req.(*DeleteJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

// JobSched_ServiceDesc is the grpc.ServiceDesc for JobSched service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobSched_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobsched.JobSched",
	HandlerType: (*JobSchedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PubJob",
			Handler:    _JobSched_PubJob_Handler,
		},
		{
			MethodName: "SetJob",
			Handler:    _JobSched_SetJob_Handler,
		},
		{
			MethodName: "SetJobsByBizId",
			Handler:    _JobSched_SetJobsByBizId_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _JobSched_StopJob_Handler,
		},
		{
			MethodName: "StopJobByUniqKey",
			Handler:    _JobSched_StopJobByUniqKey_Handler,
		},
		{
			MethodName: "StopJobsByBizId",
			Handler:    _JobSched_StopJobsByBizId_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobSched_GetJob_Handler,
		},
		{
			MethodName: "GetJobsByBizId",
			Handler:    _JobSched_GetJobsByBizId_Handler,
		},
		{
			MethodName: "GetJobByUniqKey",
			Handler:    _JobSched_GetJobByUniqKey_Handler,
		},
		{
			MethodName: "HeartBeatAsyncJob",
			Handler:    _JobSched_HeartBeatAsyncJob_Handler,
		},
		{
			MethodName: "ClearExpiredJobs",
			Handler:    _JobSched_ClearExpiredJobs_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _JobSched_DeleteJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobsched.proto",
}
