// Code generated by protoc-gen-mgorm. DO NOT EDIT.
package jobsched

import (
	"context"
	"fmt"
	"time"

	"github.com/995933447/mgorm"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

const (
	JobDbName   = "easymicrojob"
	JobTbName   = "job"
	JobConnName = "easymicrojob"
)

// 索引
var jobIndexKeys = []string{
	"biz_id",
	"uniq_key",
}

var jobUniqueIndexKeys = []string{}

var jobExpireIndexKeys = []string{}

type JobOrm struct {
	ID                             primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`
	JobId                          string             `json:"job_id,omitempty" bson:"job_id"`
	Name                           string             `json:"name,omitempty" bson:"name"`
	Status                         int32              `json:"status,omitempty" bson:"status"`
	LastSchedAt                    int64              `json:"last_sched_at,omitempty" bson:"last_sched_at"`
	LastRunAt                      int64              `json:"last_run_at,omitempty" bson:"last_run_at"`
	LastFinishRunAt                int64              `json:"last_finish_run_at,omitempty" bson:"last_finish_run_at"`
	LastSuccAt                     int64              `json:"last_succ_at,omitempty" bson:"last_succ_at"`
	LastFailAt                     int64              `json:"last_fail_at,omitempty" bson:"last_fail_at"`
	SchedCount                     uint32             `json:"sched_count,omitempty" bson:"sched_count"`
	ReSchedCountCazTimeout         uint32             `json:"re_sched_count_caz_timeout,omitempty" bson:"re_sched_count_caz_timeout"`
	ReRunCountCazFail              uint32             `json:"re_run_count_caz_fail,omitempty" bson:"re_run_count_caz_fail"`
	RunCount                       uint32             `json:"run_count,omitempty" bson:"run_count"`
	AllowReRunCountCazFailPerSched uint32             `json:"allow_re_run_count_caz_fail_per_sched,omitempty" bson:"allow_re_run_count_caz_fail_per_sched"`
	ReRunCountCazFailCurSched      uint32             `json:"re_run_count_caz_fail_cur_sched,omitempty" bson:"re_run_count_caz_fail_cur_sched"`
	SuccCount                      uint32             `json:"succ_count,omitempty" bson:"succ_count"`
	FailCount                      uint32             `json:"fail_count,omitempty" bson:"fail_count"`
	MaxRunSec                      uint32             `json:"max_run_sec,omitempty" bson:"max_run_sec"`
	GroupName                      string             `json:"group_name,omitempty" bson:"group_name"`
	GroupMaxConcur                 uint32             `json:"group_max_concur,omitempty" bson:"group_max_concur"`
	NextSchedAt                    int64              `json:"next_sched_at,omitempty" bson:"next_sched_at"`
	TimeCronExpr                   string             `json:"time_cron_expr,omitempty" bson:"time_cron_expr"`
	TimeIntervalSec                uint32             `json:"time_interval_sec,omitempty" bson:"time_interval_sec"`
	Mode                           int32              `json:"mode,omitempty" bson:"mode"`
	IsRunInAsync                   int32              `json:"is_run_in_async,omitempty" bson:"is_run_in_async"`
	LastHeartBeatInAsyncAt         int64              `json:"last_heart_beat_in_async_at,omitempty" bson:"last_heart_beat_in_async_at"`
	RpcSrv                         string             `json:"rpc_srv,omitempty" bson:"rpc_srv"`
	RpcMethod                      string             `json:"rpc_method,omitempty" bson:"rpc_method"`
	Arg                            string             `json:"arg,omitempty" bson:"arg"`
	BizId                          string             `json:"biz_id,omitempty" bson:"biz_id"`
	UniqKey                        string             `json:"uniq_key,omitempty" bson:"uniq_key"`
	LastErr                        string             `json:"last_err,omitempty" bson:"last_err"`
	LastResExtra                   string             `json:"last_res_extra,omitempty" bson:"last_res_extra"`
	CreatorTrace                   string             `json:"creator_trace,omitempty" bson:"creator_trace"`
	LastCallbackTrace              string             `json:"last_callback_trace,omitempty" bson:"last_callback_trace"`
	CreatedAt                      time.Time          `json:"created_at,omitempty" bson:"created_at,omitempty"`
	UpdatedAt                      time.Time          `json:"updated_at,omitempty" bson:"updated_at,omitempty"`
}

var jobOrmCache mgorm.Cache

func SetJobOrmCache(cache mgorm.Cache) {
	jobOrmCache = cache
}

var onJobOrmQueryDone mgorm.OnQueryDoneFunc

func SetJobOrmOnQueryDone(fn mgorm.OnQueryDoneFunc) {
	onJobOrmQueryDone = fn
}

func NewJobModel() *JobModel {
	cache := jobOrmCache
	if cache == nil {
		cache = mgorm.DefaultCache
	}
	orm := mgorm.NewOrm(
		JobConnName,
		JobDbName,
		JobTbName,
		false,
		cache,
		jobIndexKeys,
		jobUniqueIndexKeys,
		jobExpireIndexKeys,
	)
	onQueryDoneFunc := onJobOrmQueryDone
	if onQueryDoneFunc == nil {
		onQueryDoneFunc = mgorm.OnQueryDone
	}
	orm.SetOnQueryDone(onQueryDoneFunc)
	return &JobModel{
		Model: mgorm.Model[JobOrm]{
			Orm:    orm,
			Cached: false,
		},
	}
}

type JobModel struct {
	mgorm.Model[JobOrm]
}

func (m *JobModel) NormalizeOrmForInsert(data *JobOrm) {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = data.CreatedAt
}

func (m *JobModel) InsertOneIgnoreConflict(ctx context.Context, data *JobOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOneIgnoreConflict(ctx, data)
	return err
}

func (m *JobModel) InsertOne(ctx context.Context, data *JobOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOne(ctx, data)
	return err
}

func (m *JobModel) InsertMany(ctx context.Context, dataList []*JobOrm) error {
	var ins []any
	for _, data := range dataList {
		m.NormalizeOrmForInsert(data)
		ins = append(ins, data)
	}
	_, err := m.Model.InsertMany(ctx, ins)
	return err
}

func (m *JobModel) GetCacheKeys(data *JobOrm) []string {
	var cacheKeys []string
	cacheKeys = append(cacheKeys, fmt.Sprintf("_id:%s", data.ID.Hex()))
	return cacheKeys
}

func (m *JobModel) Update(ctx context.Context, data *JobOrm) (*mongo.UpdateResult, error) {
	dataB, err := mgorm.ToBsonM(data)
	if err != nil {
		return nil, err
	}
	dataB["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": dataB["_id"]}, bson.M{"$set": dataB})
}

func (m *JobModel) UpdateOne(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": data})
}

func (m *JobModel) UpdateMany(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateMany(ctx, filter, bson.M{"$set": data})
}

func (m *JobModel) Upsert(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$setOnInsert": insertData})
}

func (m *JobModel) UpInc(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$inc": data, "$set": bson.M{"updated_at": time.Now()}, "$setOnInsert": insertData})
}

func (m *JobModel) UpAndInc(ctx context.Context, filter any, data, incdata bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$inc": incdata, "$setOnInsert": insertData})
}

func (m *JobModel) DeleteOne(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteOne(ctx, filter)
}

func (m *JobModel) DeleteMany(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteMany(ctx, filter)
}

func (m *JobModel) UpdateOneByID(ctx context.Context, id string, data bson.M) (*mongo.UpdateResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": objId}, bson.M{"$set": data})
}

func (m *JobModel) DeleteOneByID(ctx context.Context, id string) (*mongo.DeleteResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	return m.Model.DeleteOne(ctx, bson.M{"_id": objId})
}

func (m *JobModel) FindOneByID(ctx context.Context, id string) (*JobOrm, error) {
	var data JobOrm
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	filter := bson.M{"_id": objId}
	cacheKey := fmt.Sprintf("_id:%s", id)
	err = m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (m *JobModel) FindManyByBizId(ctx context.Context, bizId string, sort bson.D, limit int64, selectors ...any) ([]*JobOrm, error) {
	filter := bson.M{}
	filter["biz_id"] = bizId
	return m.Model.FindMany(ctx, filter, sort, limit, selectors...)
}

func (m *JobModel) FindManyPageByBizId(ctx context.Context, bizId string, sort bson.D, page, pageSize int64, selectors ...any) ([]*JobOrm, error) {
	filter := bson.M{}
	filter["biz_id"] = bizId
	skip := (page - 1) * pageSize
	if skip < 0 {
		skip = 0
	}
	return m.Model.FindManyByPage(ctx, filter, sort, skip, pageSize, selectors...)
}

func (m *JobModel) FindAllByBizId(ctx context.Context, bizId string, sort bson.D, selectors ...any) ([]*JobOrm, error) {
	filter := bson.M{}
	filter["biz_id"] = bizId
	return m.Model.FindAllBySort(ctx, filter, sort, selectors...)
}

func (m *JobModel) UpdateManyByBizId(ctx context.Context, bizId string, data bson.M) (*mongo.UpdateResult, error) {
	filter := bson.M{}
	filter["biz_id"] = bizId
	return m.UpdateMany(ctx, filter, data)
}

func (m *JobModel) DeleteManyByBizId(ctx context.Context, bizId string) (*mongo.DeleteResult, error) {
	filter := bson.M{}
	filter["biz_id"] = bizId
	return m.DeleteMany(ctx, filter)
}

func (m *JobModel) FindManyByUniqKey(ctx context.Context, uniqKey string, sort bson.D, limit int64, selectors ...any) ([]*JobOrm, error) {
	filter := bson.M{}
	filter["uniq_key"] = uniqKey
	return m.Model.FindMany(ctx, filter, sort, limit, selectors...)
}

func (m *JobModel) FindManyPageByUniqKey(ctx context.Context, uniqKey string, sort bson.D, page, pageSize int64, selectors ...any) ([]*JobOrm, error) {
	filter := bson.M{}
	filter["uniq_key"] = uniqKey
	skip := (page - 1) * pageSize
	if skip < 0 {
		skip = 0
	}
	return m.Model.FindManyByPage(ctx, filter, sort, skip, pageSize, selectors...)
}

func (m *JobModel) FindAllByUniqKey(ctx context.Context, uniqKey string, sort bson.D, selectors ...any) ([]*JobOrm, error) {
	filter := bson.M{}
	filter["uniq_key"] = uniqKey
	return m.Model.FindAllBySort(ctx, filter, sort, selectors...)
}

func (m *JobModel) UpdateManyByUniqKey(ctx context.Context, uniqKey string, data bson.M) (*mongo.UpdateResult, error) {
	filter := bson.M{}
	filter["uniq_key"] = uniqKey
	return m.UpdateMany(ctx, filter, data)
}

func (m *JobModel) DeleteManyByUniqKey(ctx context.Context, uniqKey string) (*mongo.DeleteResult, error) {
	filter := bson.M{}
	filter["uniq_key"] = uniqKey
	return m.DeleteMany(ctx, filter)
}

const (
	JobGroupDbName   = "easymicrojob"
	JobGroupTbName   = "job_group"
	JobGroupConnName = "easymicrojob"
)

// 索引
var jobGroupIndexKeys = []string{}

var jobGroupUniqueIndexKeys = []string{
	"name",
}

var jobGroupExpireIndexKeys = []string{}

type JobGroupOrm struct {
	ID        primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`
	Name      string             `json:"name,omitempty" bson:"name"`
	MaxConcur uint32             `json:"max_concur,omitempty" bson:"max_concur"`
	CreatedAt time.Time          `json:"created_at,omitempty" bson:"created_at,omitempty"`
	UpdatedAt time.Time          `json:"updated_at,omitempty" bson:"updated_at,omitempty"`
}

var jobGroupOrmCache mgorm.Cache

func SetJobGroupOrmCache(cache mgorm.Cache) {
	jobGroupOrmCache = cache
}

var onJobGroupOrmQueryDone mgorm.OnQueryDoneFunc

func SetJobGroupOrmOnQueryDone(fn mgorm.OnQueryDoneFunc) {
	onJobGroupOrmQueryDone = fn
}

func NewJobGroupModel() *JobGroupModel {
	cache := jobGroupOrmCache
	if cache == nil {
		cache = mgorm.DefaultCache
	}
	orm := mgorm.NewOrm(
		JobGroupConnName,
		JobGroupDbName,
		JobGroupTbName,
		false,
		cache,
		jobGroupIndexKeys,
		jobGroupUniqueIndexKeys,
		jobGroupExpireIndexKeys,
	)
	onQueryDoneFunc := onJobGroupOrmQueryDone
	if onQueryDoneFunc == nil {
		onQueryDoneFunc = mgorm.OnQueryDone
	}
	orm.SetOnQueryDone(onQueryDoneFunc)
	return &JobGroupModel{
		Model: mgorm.Model[JobGroupOrm]{
			Orm:    orm,
			Cached: false,
		},
	}
}

type JobGroupModel struct {
	mgorm.Model[JobGroupOrm]
}

func (m *JobGroupModel) NormalizeOrmForInsert(data *JobGroupOrm) {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = data.CreatedAt
}

func (m *JobGroupModel) InsertOneIgnoreConflict(ctx context.Context, data *JobGroupOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOneIgnoreConflict(ctx, data)
	return err
}

func (m *JobGroupModel) InsertOne(ctx context.Context, data *JobGroupOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOne(ctx, data)
	return err
}

func (m *JobGroupModel) InsertMany(ctx context.Context, dataList []*JobGroupOrm) error {
	var ins []any
	for _, data := range dataList {
		m.NormalizeOrmForInsert(data)
		ins = append(ins, data)
	}
	_, err := m.Model.InsertMany(ctx, ins)
	return err
}

func (m *JobGroupModel) GetCacheKeys(data *JobGroupOrm) []string {
	var cacheKeys []string
	cacheKeys = append(cacheKeys, fmt.Sprintf("_id:%s", data.ID.Hex()))
	cacheKeys = append(cacheKeys, fmt.Sprintf(
		"name:%s", data.Name,
	))
	return cacheKeys
}

func (m *JobGroupModel) Update(ctx context.Context, data *JobGroupOrm) (*mongo.UpdateResult, error) {
	dataB, err := mgorm.ToBsonM(data)
	if err != nil {
		return nil, err
	}
	dataB["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": dataB["_id"]}, bson.M{"$set": dataB})
}

func (m *JobGroupModel) UpdateOne(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": data})
}

func (m *JobGroupModel) UpdateMany(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateMany(ctx, filter, bson.M{"$set": data})
}

func (m *JobGroupModel) Upsert(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$setOnInsert": insertData})
}

func (m *JobGroupModel) UpInc(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$inc": data, "$set": bson.M{"updated_at": time.Now()}, "$setOnInsert": insertData})
}

func (m *JobGroupModel) UpAndInc(ctx context.Context, filter any, data, incdata bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$inc": incdata, "$setOnInsert": insertData})
}

func (m *JobGroupModel) DeleteOne(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteOne(ctx, filter)
}

func (m *JobGroupModel) DeleteMany(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteMany(ctx, filter)
}

func (m *JobGroupModel) UpdateOneByID(ctx context.Context, id string, data bson.M) (*mongo.UpdateResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": objId}, bson.M{"$set": data})
}

func (m *JobGroupModel) DeleteOneByID(ctx context.Context, id string) (*mongo.DeleteResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	return m.Model.DeleteOne(ctx, bson.M{"_id": objId})
}

func (m *JobGroupModel) FindOneByID(ctx context.Context, id string) (*JobGroupOrm, error) {
	var data JobGroupOrm
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	filter := bson.M{"_id": objId}
	cacheKey := fmt.Sprintf("_id:%s", id)
	err = m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (m *JobGroupModel) UpdateOneByName(ctx context.Context, name string, update bson.M) (*mongo.UpdateResult, error) {
	filter := bson.M{}
	var data JobGroupOrm
	filter["name"] = name
	cacheKey := fmt.Sprintf(
		"name:%s",
		name,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(&data))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}

	update["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": update})
}

func (m *JobGroupModel) FindOneByName(ctx context.Context, name string) (*JobGroupOrm, error) {
	var data JobGroupOrm
	filter := bson.M{}
	filter["name"] = name
	cacheKey := fmt.Sprintf(
		"name:%s",
		name,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (m *JobGroupModel) DeleteOneByName(ctx context.Context, name string) (*mongo.DeleteResult, error) {
	var data JobGroupOrm
	filter := bson.M{}
	filter["name"] = name
	cacheKey := fmt.Sprintf(
		"name:%s",
		name,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(&data))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}
	return m.Model.DeleteOne(ctx, filter)
}
