// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: jobsched.proto

package jobsched

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedJobMode int32

const (
	SchedJobMode_SchedJobModeNil             SchedJobMode = 0
	SchedJobMode_SchedJobModeSpecTime        SchedJobMode = 1 // 调度模式为指定时间戳
	SchedJobMode_SchedJobModeTimeCron        SchedJobMode = 2 // 调度模式为crontab粗发
	SchedJobMode_SchedJobModeTimeIntervalSec SchedJobMode = 3 // 调度模式间隔n秒触发一次
)

// Enum value maps for SchedJobMode.
var (
	SchedJobMode_name = map[int32]string{
		0: "SchedJobModeNil",
		1: "SchedJobModeSpecTime",
		2: "SchedJobModeTimeCron",
		3: "SchedJobModeTimeIntervalSec",
	}
	SchedJobMode_value = map[string]int32{
		"SchedJobModeNil":             0,
		"SchedJobModeSpecTime":        1,
		"SchedJobModeTimeCron":        2,
		"SchedJobModeTimeIntervalSec": 3,
	}
)

func (x SchedJobMode) Enum() *SchedJobMode {
	p := new(SchedJobMode)
	*p = x
	return p
}

func (x SchedJobMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedJobMode) Descriptor() protoreflect.EnumDescriptor {
	return file_jobsched_proto_enumTypes[0].Descriptor()
}

func (SchedJobMode) Type() protoreflect.EnumType {
	return &file_jobsched_proto_enumTypes[0]
}

func (x SchedJobMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedJobMode.Descriptor instead.
func (SchedJobMode) EnumDescriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{0}
}

type ErrCode int32

const (
	ErrCode_ErrCodeNil          ErrCode = 0
	ErrCode_ErrCodeParamInvalid ErrCode = 5001
	ErrCode_ErrCodeJobNotFound  ErrCode = 5002
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ErrCodeNil",
		5001: "ErrCodeParamInvalid",
		5002: "ErrCodeJobNotFound",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":          0,
		"ErrCodeParamInvalid": 5001,
		"ErrCodeJobNotFound":  5002,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_jobsched_proto_enumTypes[1].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_jobsched_proto_enumTypes[1]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{1}
}

type SchedJobStatus int32

const (
	SchedJobStatus_SchedJobStatusNil          SchedJobStatus = 0
	SchedJobStatus_SchedJobStatusSched        SchedJobStatus = 1
	SchedJobStatus_SchedJobStatusRunning      SchedJobStatus = 2
	SchedJobStatus_SchedJobStatusFinish       SchedJobStatus = 3
	SchedJobStatus_SchedJobStatusStopped      SchedJobStatus = 4
	SchedJobStatus_SchedJobStatusRunningAsync SchedJobStatus = 5
	SchedJobStatus_SchedJobStatusFail         SchedJobStatus = 6
)

// Enum value maps for SchedJobStatus.
var (
	SchedJobStatus_name = map[int32]string{
		0: "SchedJobStatusNil",
		1: "SchedJobStatusSched",
		2: "SchedJobStatusRunning",
		3: "SchedJobStatusFinish",
		4: "SchedJobStatusStopped",
		5: "SchedJobStatusRunningAsync",
		6: "SchedJobStatusFail",
	}
	SchedJobStatus_value = map[string]int32{
		"SchedJobStatusNil":          0,
		"SchedJobStatusSched":        1,
		"SchedJobStatusRunning":      2,
		"SchedJobStatusFinish":       3,
		"SchedJobStatusStopped":      4,
		"SchedJobStatusRunningAsync": 5,
		"SchedJobStatusFail":         6,
	}
)

func (x SchedJobStatus) Enum() *SchedJobStatus {
	p := new(SchedJobStatus)
	*p = x
	return p
}

func (x SchedJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jobsched_proto_enumTypes[2].Descriptor()
}

func (SchedJobStatus) Type() protoreflect.EnumType {
	return &file_jobsched_proto_enumTypes[2]
}

func (x SchedJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedJobStatus.Descriptor instead.
func (SchedJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{2}
}

type DeleteJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobReq) Reset() {
	*x = DeleteJobReq{}
	mi := &file_jobsched_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobReq) ProtoMessage() {}

func (x *DeleteJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobReq.ProtoReflect.Descriptor instead.
func (*DeleteJobReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type DeleteJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobResp) Reset() {
	*x = DeleteJobResp{}
	mi := &file_jobsched_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobResp) ProtoMessage() {}

func (x *DeleteJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobResp.ProtoReflect.Descriptor instead.
func (*DeleteJobResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{1}
}

type ClearExpiredJobsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearExpiredJobsReq) Reset() {
	*x = ClearExpiredJobsReq{}
	mi := &file_jobsched_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearExpiredJobsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearExpiredJobsReq) ProtoMessage() {}

func (x *ClearExpiredJobsReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearExpiredJobsReq.ProtoReflect.Descriptor instead.
func (*ClearExpiredJobsReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{2}
}

type ClearExpiredJobsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearExpiredJobsResp) Reset() {
	*x = ClearExpiredJobsResp{}
	mi := &file_jobsched_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearExpiredJobsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearExpiredJobsResp) ProtoMessage() {}

func (x *ClearExpiredJobsResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearExpiredJobsResp.ProtoReflect.Descriptor instead.
func (*ClearExpiredJobsResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{3}
}

type PubJobReq struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Name                           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                                        // 作业名称
	JobGroup                       string                 `protobuf:"bytes,2,opt,name=job_group,json=jobGroup,proto3" json:"job_group,omitempty"`                                                                                // 作业分组
	JobGroupMaxConcur              uint32                 `protobuf:"varint,3,opt,name=job_group_max_concur,json=jobGroupMaxConcur,proto3" json:"job_group_max_concur,omitempty"`                                                // 作业组最大并发数
	Mode                           int32                  `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                                                                                                       // 模式，执行模式.1.指定时间戳（只运行一次）,2.cron表达式（持续间隔触发）(*/5 * * * * * *:时钟每五秒触发，0 */5 * * * * *：时钟每5分第0秒触发), 3.间隔执行（持续间隔出发）
	TimeCronExpr                   string                 `protobuf:"bytes,5,opt,name=time_cron_expr,json=timeCronExpr,proto3" json:"time_cron_expr,omitempty"`                                                                  // cron表达式（mode为2时候有效）
	TimeIntervalSec                uint32                 `protobuf:"varint,6,opt,name=time_interval_sec,json=timeIntervalSec,proto3" json:"time_interval_sec,omitempty"`                                                        // 间隔n秒执行一次 （mode为3时候有效）
	SpecTimeAt                     int64                  `protobuf:"varint,7,opt,name=spec_time_at,json=specTimeAt,proto3" json:"spec_time_at,omitempty"`                                                                       // 指定时间执行（mode为1时候有效）
	AllowReRunCountCazFailPerSched uint32                 `protobuf:"varint,8,opt,name=allow_re_run_count_caz_fail_per_sched,json=allowReRunCountCazFailPerSched,proto3" json:"allow_re_run_count_caz_fail_per_sched,omitempty"` // 每轮调度允许失败重试的最大次数
	RpcSrv                         string                 `protobuf:"bytes,9,opt,name=rpc_srv,json=rpcSrv,proto3" json:"rpc_srv,omitempty"`                                                                                      // rpc服务
	RpcMethod                      string                 `protobuf:"bytes,10,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpc_method,omitempty"`                                                                            // rpc方法
	Arg                            string                 `protobuf:"bytes,11,opt,name=arg,proto3" json:"arg,omitempty"`                                                                                                         // 任务参数,保存是要更新的内容
	BizId                          string                 `protobuf:"bytes,12,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`                                                                                        // 自定义用于指定任务业务id，由开发人员自己定（不是真的仅仅指账变账单id）
	UniqKey                        string                 `protobuf:"bytes,13,opt,name=uniq_key,json=uniqKey,proto3" json:"uniq_key,omitempty"`                                                                                  // 自定义唯一id
	MaxRunSec                      uint32                 `protobuf:"varint,14,opt,name=max_run_sec,json=maxRunSec,proto3" json:"max_run_sec,omitempty"`                                                                         // 最长运行时间，超过20秒请使用异步方式，同步方式将强制最长仅能运行20秒，建议耗时任务直接使用异步模式
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *PubJobReq) Reset() {
	*x = PubJobReq{}
	mi := &file_jobsched_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubJobReq) ProtoMessage() {}

func (x *PubJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubJobReq.ProtoReflect.Descriptor instead.
func (*PubJobReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{4}
}

func (x *PubJobReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PubJobReq) GetJobGroup() string {
	if x != nil {
		return x.JobGroup
	}
	return ""
}

func (x *PubJobReq) GetJobGroupMaxConcur() uint32 {
	if x != nil {
		return x.JobGroupMaxConcur
	}
	return 0
}

func (x *PubJobReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PubJobReq) GetTimeCronExpr() string {
	if x != nil {
		return x.TimeCronExpr
	}
	return ""
}

func (x *PubJobReq) GetTimeIntervalSec() uint32 {
	if x != nil {
		return x.TimeIntervalSec
	}
	return 0
}

func (x *PubJobReq) GetSpecTimeAt() int64 {
	if x != nil {
		return x.SpecTimeAt
	}
	return 0
}

func (x *PubJobReq) GetAllowReRunCountCazFailPerSched() uint32 {
	if x != nil {
		return x.AllowReRunCountCazFailPerSched
	}
	return 0
}

func (x *PubJobReq) GetRpcSrv() string {
	if x != nil {
		return x.RpcSrv
	}
	return ""
}

func (x *PubJobReq) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

func (x *PubJobReq) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *PubJobReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *PubJobReq) GetUniqKey() string {
	if x != nil {
		return x.UniqKey
	}
	return ""
}

func (x *PubJobReq) GetMaxRunSec() uint32 {
	if x != nil {
		return x.MaxRunSec
	}
	return 0
}

type PubJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubJobResp) Reset() {
	*x = PubJobResp{}
	mi := &file_jobsched_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubJobResp) ProtoMessage() {}

func (x *PubJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubJobResp.ProtoReflect.Descriptor instead.
func (*PubJobResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{5}
}

func (x *PubJobResp) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type SetJobReq struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	JobId                          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobGroup                       string                 `protobuf:"bytes,2,opt,name=job_group,json=jobGroup,proto3" json:"job_group,omitempty"`                                                                                // 作业分组
	JobGroupMaxConcur              uint32                 `protobuf:"varint,3,opt,name=job_group_max_concur,json=jobGroupMaxConcur,proto3" json:"job_group_max_concur,omitempty"`                                                // 作业组最大并发数
	Mode                           int32                  `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                                                                                                       // 模式，执行模式.1.指定时间戳（只运行一次）,2.cron表达式（持续间隔触发） 3.间隔执行（持续间隔出发）
	TimeCronExpr                   string                 `protobuf:"bytes,5,opt,name=time_cron_expr,json=timeCronExpr,proto3" json:"time_cron_expr,omitempty"`                                                                  // cron表达式（mode为2时候有效）
	TimeIntervalSec                uint32                 `protobuf:"varint,6,opt,name=time_interval_sec,json=timeIntervalSec,proto3" json:"time_interval_sec,omitempty"`                                                        // 间隔n秒执行一次 （mode为3时候有效）
	SpecTimeAt                     int64                  `protobuf:"varint,7,opt,name=spec_time_at,json=specTimeAt,proto3" json:"spec_time_at,omitempty"`                                                                       // 指定时间执行（mode为1时候有效）
	AllowReRunCountCazFailPerSched uint32                 `protobuf:"varint,8,opt,name=allow_re_run_count_caz_fail_per_sched,json=allowReRunCountCazFailPerSched,proto3" json:"allow_re_run_count_caz_fail_per_sched,omitempty"` // 每轮调度允许失败重试的最大次数
	RpcSrv                         string                 `protobuf:"bytes,9,opt,name=rpc_srv,json=rpcSrv,proto3" json:"rpc_srv,omitempty"`                                                                                      // rpc服务
	RpcMethod                      string                 `protobuf:"bytes,10,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpc_method,omitempty"`                                                                            // rpc方法
	Arg                            string                 `protobuf:"bytes,11,opt,name=arg,proto3" json:"arg,omitempty"`                                                                                                         // 参数
	MaxRunSec                      uint32                 `protobuf:"varint,12,opt,name=max_run_sec,json=maxRunSec,proto3" json:"max_run_sec,omitempty"`                                                                         // 最长运行时间
	BizId                          string                 `protobuf:"bytes,13,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *SetJobReq) Reset() {
	*x = SetJobReq{}
	mi := &file_jobsched_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobReq) ProtoMessage() {}

func (x *SetJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobReq.ProtoReflect.Descriptor instead.
func (*SetJobReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{6}
}

func (x *SetJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SetJobReq) GetJobGroup() string {
	if x != nil {
		return x.JobGroup
	}
	return ""
}

func (x *SetJobReq) GetJobGroupMaxConcur() uint32 {
	if x != nil {
		return x.JobGroupMaxConcur
	}
	return 0
}

func (x *SetJobReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SetJobReq) GetTimeCronExpr() string {
	if x != nil {
		return x.TimeCronExpr
	}
	return ""
}

func (x *SetJobReq) GetTimeIntervalSec() uint32 {
	if x != nil {
		return x.TimeIntervalSec
	}
	return 0
}

func (x *SetJobReq) GetSpecTimeAt() int64 {
	if x != nil {
		return x.SpecTimeAt
	}
	return 0
}

func (x *SetJobReq) GetAllowReRunCountCazFailPerSched() uint32 {
	if x != nil {
		return x.AllowReRunCountCazFailPerSched
	}
	return 0
}

func (x *SetJobReq) GetRpcSrv() string {
	if x != nil {
		return x.RpcSrv
	}
	return ""
}

func (x *SetJobReq) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

func (x *SetJobReq) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *SetJobReq) GetMaxRunSec() uint32 {
	if x != nil {
		return x.MaxRunSec
	}
	return 0
}

func (x *SetJobReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

type SetJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobResp) Reset() {
	*x = SetJobResp{}
	mi := &file_jobsched_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobResp) ProtoMessage() {}

func (x *SetJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobResp.ProtoReflect.Descriptor instead.
func (*SetJobResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{7}
}

type SetJobsByBizIdReq struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	BizId                          string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	JobGroup                       string                 `protobuf:"bytes,2,opt,name=job_group,json=jobGroup,proto3" json:"job_group,omitempty"`                                                                                // 作业分组
	JobGroupMaxConcur              uint32                 `protobuf:"varint,3,opt,name=job_group_max_concur,json=jobGroupMaxConcur,proto3" json:"job_group_max_concur,omitempty"`                                                // 作业组最大并发数
	Mode                           int32                  `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                                                                                                       // 模式，执行模式.1.指定时间戳（只运行一次）,2.cron表达式（持续间隔触发） 3.间隔执行（持续间隔出发）
	TimeCronExpr                   string                 `protobuf:"bytes,5,opt,name=time_cron_expr,json=timeCronExpr,proto3" json:"time_cron_expr,omitempty"`                                                                  // cron表达式（mode为2时候有效）
	TimeIntervalSec                uint32                 `protobuf:"varint,6,opt,name=time_interval_sec,json=timeIntervalSec,proto3" json:"time_interval_sec,omitempty"`                                                        // 间隔n秒执行一次 （mode为3时候有效）
	SpecTimeAt                     int64                  `protobuf:"varint,7,opt,name=spec_time_at,json=specTimeAt,proto3" json:"spec_time_at,omitempty"`                                                                       // 指定时间执行（mode为1时候有效）
	AllowReRunCountCazFailPerSched uint32                 `protobuf:"varint,8,opt,name=allow_re_run_count_caz_fail_per_sched,json=allowReRunCountCazFailPerSched,proto3" json:"allow_re_run_count_caz_fail_per_sched,omitempty"` // 每轮调度允许失败重试的最大次数
	RpcSrv                         string                 `protobuf:"bytes,9,opt,name=rpc_srv,json=rpcSrv,proto3" json:"rpc_srv,omitempty"`                                                                                      // rpc服务
	RpcMethod                      string                 `protobuf:"bytes,10,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpc_method,omitempty"`                                                                            // rpc方法
	Arg                            string                 `protobuf:"bytes,11,opt,name=arg,proto3" json:"arg,omitempty"`                                                                                                         // 参数
	MaxRunSec                      uint32                 `protobuf:"varint,12,opt,name=max_run_sec,json=maxRunSec,proto3" json:"max_run_sec,omitempty"`                                                                         // 最长运行时间
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *SetJobsByBizIdReq) Reset() {
	*x = SetJobsByBizIdReq{}
	mi := &file_jobsched_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobsByBizIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobsByBizIdReq) ProtoMessage() {}

func (x *SetJobsByBizIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobsByBizIdReq.ProtoReflect.Descriptor instead.
func (*SetJobsByBizIdReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{8}
}

func (x *SetJobsByBizIdReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *SetJobsByBizIdReq) GetJobGroup() string {
	if x != nil {
		return x.JobGroup
	}
	return ""
}

func (x *SetJobsByBizIdReq) GetJobGroupMaxConcur() uint32 {
	if x != nil {
		return x.JobGroupMaxConcur
	}
	return 0
}

func (x *SetJobsByBizIdReq) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SetJobsByBizIdReq) GetTimeCronExpr() string {
	if x != nil {
		return x.TimeCronExpr
	}
	return ""
}

func (x *SetJobsByBizIdReq) GetTimeIntervalSec() uint32 {
	if x != nil {
		return x.TimeIntervalSec
	}
	return 0
}

func (x *SetJobsByBizIdReq) GetSpecTimeAt() int64 {
	if x != nil {
		return x.SpecTimeAt
	}
	return 0
}

func (x *SetJobsByBizIdReq) GetAllowReRunCountCazFailPerSched() uint32 {
	if x != nil {
		return x.AllowReRunCountCazFailPerSched
	}
	return 0
}

func (x *SetJobsByBizIdReq) GetRpcSrv() string {
	if x != nil {
		return x.RpcSrv
	}
	return ""
}

func (x *SetJobsByBizIdReq) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

func (x *SetJobsByBizIdReq) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *SetJobsByBizIdReq) GetMaxRunSec() uint32 {
	if x != nil {
		return x.MaxRunSec
	}
	return 0
}

type SetJobsByBizIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasMore       bool                   `protobuf:"varint,1,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobsByBizIdResp) Reset() {
	*x = SetJobsByBizIdResp{}
	mi := &file_jobsched_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobsByBizIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobsByBizIdResp) ProtoMessage() {}

func (x *SetJobsByBizIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobsByBizIdResp.ProtoReflect.Descriptor instead.
func (*SetJobsByBizIdResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{9}
}

func (x *SetJobsByBizIdResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type StopJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobReq) Reset() {
	*x = StopJobReq{}
	mi := &file_jobsched_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobReq) ProtoMessage() {}

func (x *StopJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobReq.ProtoReflect.Descriptor instead.
func (*StopJobReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{10}
}

func (x *StopJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StopJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobResp) Reset() {
	*x = StopJobResp{}
	mi := &file_jobsched_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobResp) ProtoMessage() {}

func (x *StopJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobResp.ProtoReflect.Descriptor instead.
func (*StopJobResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{11}
}

type StopJobByUniqKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqKey       string                 `protobuf:"bytes,1,opt,name=uniq_key,json=uniqKey,proto3" json:"uniq_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobByUniqKeyReq) Reset() {
	*x = StopJobByUniqKeyReq{}
	mi := &file_jobsched_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobByUniqKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobByUniqKeyReq) ProtoMessage() {}

func (x *StopJobByUniqKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobByUniqKeyReq.ProtoReflect.Descriptor instead.
func (*StopJobByUniqKeyReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{12}
}

func (x *StopJobByUniqKeyReq) GetUniqKey() string {
	if x != nil {
		return x.UniqKey
	}
	return ""
}

type StopJobByUniqKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobByUniqKeyResp) Reset() {
	*x = StopJobByUniqKeyResp{}
	mi := &file_jobsched_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobByUniqKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobByUniqKeyResp) ProtoMessage() {}

func (x *StopJobByUniqKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobByUniqKeyResp.ProtoReflect.Descriptor instead.
func (*StopJobByUniqKeyResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{13}
}

type StopJobsByBizIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobsByBizIdReq) Reset() {
	*x = StopJobsByBizIdReq{}
	mi := &file_jobsched_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobsByBizIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobsByBizIdReq) ProtoMessage() {}

func (x *StopJobsByBizIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobsByBizIdReq.ProtoReflect.Descriptor instead.
func (*StopJobsByBizIdReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{14}
}

func (x *StopJobsByBizIdReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

type StopJobsByBizIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasMore       bool                   `protobuf:"varint,1,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobsByBizIdResp) Reset() {
	*x = StopJobsByBizIdResp{}
	mi := &file_jobsched_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobsByBizIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobsByBizIdResp) ProtoMessage() {}

func (x *StopJobsByBizIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobsByBizIdResp.ProtoReflect.Descriptor instead.
func (*StopJobsByBizIdResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{15}
}

func (x *StopJobsByBizIdResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type HeartBeatAsyncJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 作业id
	Finish        bool                   `protobuf:"varint,2,opt,name=finish,proto3" json:"finish,omitempty"`           // 是否完成
	Extra         string                 `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`              // 额外响应
	Err           string                 `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`                  // 作业错误
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatAsyncJobReq) Reset() {
	*x = HeartBeatAsyncJobReq{}
	mi := &file_jobsched_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatAsyncJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatAsyncJobReq) ProtoMessage() {}

func (x *HeartBeatAsyncJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatAsyncJobReq.ProtoReflect.Descriptor instead.
func (*HeartBeatAsyncJobReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{16}
}

func (x *HeartBeatAsyncJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartBeatAsyncJobReq) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

func (x *HeartBeatAsyncJobReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *HeartBeatAsyncJobReq) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type HeartBeatAsyncJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatAsyncJobResp) Reset() {
	*x = HeartBeatAsyncJobResp{}
	mi := &file_jobsched_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatAsyncJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatAsyncJobResp) ProtoMessage() {}

func (x *HeartBeatAsyncJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatAsyncJobResp.ProtoReflect.Descriptor instead.
func (*HeartBeatAsyncJobResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{17}
}

type GetJobByUniqKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqKey       string                 `protobuf:"bytes,1,opt,name=uniq_key,json=uniqKey,proto3" json:"uniq_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobByUniqKeyReq) Reset() {
	*x = GetJobByUniqKeyReq{}
	mi := &file_jobsched_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobByUniqKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobByUniqKeyReq) ProtoMessage() {}

func (x *GetJobByUniqKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobByUniqKeyReq.ProtoReflect.Descriptor instead.
func (*GetJobByUniqKeyReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{18}
}

func (x *GetJobByUniqKeyReq) GetUniqKey() string {
	if x != nil {
		return x.UniqKey
	}
	return ""
}

type GetJobByUniqKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobByUniqKeyResp) Reset() {
	*x = GetJobByUniqKeyResp{}
	mi := &file_jobsched_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobByUniqKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobByUniqKeyResp) ProtoMessage() {}

func (x *GetJobByUniqKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobByUniqKeyResp.ProtoReflect.Descriptor instead.
func (*GetJobByUniqKeyResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{19}
}

func (x *GetJobByUniqKeyResp) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobsByBizIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"` // 作业业务id
	Page          *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	NeedCalcTotal bool                   `protobuf:"varint,3,opt,name=need_calc_total,json=needCalcTotal,proto3" json:"need_calc_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobsByBizIdReq) Reset() {
	*x = GetJobsByBizIdReq{}
	mi := &file_jobsched_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobsByBizIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsByBizIdReq) ProtoMessage() {}

func (x *GetJobsByBizIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsByBizIdReq.ProtoReflect.Descriptor instead.
func (*GetJobsByBizIdReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{20}
}

func (x *GetJobsByBizIdReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *GetJobsByBizIdReq) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetJobsByBizIdReq) GetNeedCalcTotal() bool {
	if x != nil {
		return x.NeedCalcTotal
	}
	return false
}

type GetJobsByBizIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Page          *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobsByBizIdResp) Reset() {
	*x = GetJobsByBizIdResp{}
	mi := &file_jobsched_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobsByBizIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsByBizIdResp) ProtoMessage() {}

func (x *GetJobsByBizIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsByBizIdResp.ProtoReflect.Descriptor instead.
func (*GetJobsByBizIdResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{21}
}

func (x *GetJobsByBizIdResp) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *GetJobsByBizIdResp) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetJobsByBizIdResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobReq) Reset() {
	*x = GetJobReq{}
	mi := &file_jobsched_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobReq) ProtoMessage() {}

func (x *GetJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobReq.ProtoReflect.Descriptor instead.
func (*GetJobReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{22}
}

func (x *GetJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResp) Reset() {
	*x = GetJobResp{}
	mi := &file_jobsched_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResp) ProtoMessage() {}

func (x *GetJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResp.ProtoReflect.Descriptor instead.
func (*GetJobResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{23}
}

func (x *GetJobResp) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type DelJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelJobReq) Reset() {
	*x = DelJobReq{}
	mi := &file_jobsched_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelJobReq) ProtoMessage() {}

func (x *DelJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelJobReq.ProtoReflect.Descriptor instead.
func (*DelJobReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{24}
}

func (x *DelJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type DelJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelJobResp) Reset() {
	*x = DelJobResp{}
	mi := &file_jobsched_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelJobResp) ProtoMessage() {}

func (x *DelJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelJobResp.ProtoReflect.Descriptor instead.
func (*DelJobResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{25}
}

type DelJobByUniqKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqKey       string                 `protobuf:"bytes,1,opt,name=uniq_key,json=uniqKey,proto3" json:"uniq_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelJobByUniqKeyReq) Reset() {
	*x = DelJobByUniqKeyReq{}
	mi := &file_jobsched_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelJobByUniqKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelJobByUniqKeyReq) ProtoMessage() {}

func (x *DelJobByUniqKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelJobByUniqKeyReq.ProtoReflect.Descriptor instead.
func (*DelJobByUniqKeyReq) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{26}
}

func (x *DelJobByUniqKeyReq) GetUniqKey() string {
	if x != nil {
		return x.UniqKey
	}
	return ""
}

type DelJobByUniqKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelJobByUniqKeyResp) Reset() {
	*x = DelJobByUniqKeyResp{}
	mi := &file_jobsched_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelJobByUniqKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelJobByUniqKeyResp) ProtoMessage() {}

func (x *DelJobByUniqKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelJobByUniqKeyResp.ProtoReflect.Descriptor instead.
func (*DelJobByUniqKeyResp) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{27}
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_jobsched_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{28}
}

func (x *Page) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Page) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Job struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	JobId                          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 作业id
	Name                           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status                         int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                                                                                    // 状态，0.等待调度，1.就绪状态，2.运行中，3.已完成. 4.已停止, 5.运步运行中
	LastSchedAt                    int64                  `protobuf:"varint,4,opt,name=last_sched_at,json=lastSchedAt,proto3" json:"last_sched_at,omitempty"`                                                                     // 上次调度时间
	LastRunAt                      int64                  `protobuf:"varint,5,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`                                                                           // 上次运行时间
	LastFinishRunAt                int64                  `protobuf:"varint,6,opt,name=last_finish_run_at,json=lastFinishRunAt,proto3" json:"last_finish_run_at,omitempty"`                                                       // 上次完成运行时间
	LastSuccAt                     int64                  `protobuf:"varint,7,opt,name=last_succ_at,json=lastSuccAt,proto3" json:"last_succ_at,omitempty"`                                                                        // 任务完成时间
	LastFailAt                     int64                  `protobuf:"varint,8,opt,name=last_fail_at,json=lastFailAt,proto3" json:"last_fail_at,omitempty"`                                                                        // 上次失败时间
	SchedCount                     uint32                 `protobuf:"varint,9,opt,name=sched_count,json=schedCount,proto3" json:"sched_count,omitempty"`                                                                          // 调度次数
	ReSchedCountCazTimeout         uint32                 `protobuf:"varint,10,opt,name=re_sched_count_caz_timeout,json=reSchedCountCazTimeout,proto3" json:"re_sched_count_caz_timeout,omitempty"`                               // 任务执行超时重试调度次数
	ReRunCountCazFail              uint32                 `protobuf:"varint,11,opt,name=re_run_count_caz_fail,json=reRunCountCazFail,proto3" json:"re_run_count_caz_fail,omitempty"`                                              // 任务失败超时重试运行次数
	RunCount                       uint32                 `protobuf:"varint,12,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`                                                                               // 运行次数
	AllowReRunCountCazFailPerSched uint32                 `protobuf:"varint,13,opt,name=allow_re_run_count_caz_fail_per_sched,json=allowReRunCountCazFailPerSched,proto3" json:"allow_re_run_count_caz_fail_per_sched,omitempty"` // 每轮调度允许失败重试的最大次数
	ReRunCountCazFailCurSched      uint32                 `protobuf:"varint,14,opt,name=re_run_count_caz_fail_cur_sched,json=reRunCountCazFailCurSched,proto3" json:"re_run_count_caz_fail_cur_sched,omitempty"`                  // 本轮调度已经失败重试的次数,异步模式下无效
	SuccCount                      uint32                 `protobuf:"varint,15,opt,name=succ_count,json=succCount,proto3" json:"succ_count,omitempty"`                                                                            // 成功次数
	FailCount                      uint32                 `protobuf:"varint,16,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`                                                                            // 失败次数
	MaxRunSec                      uint32                 `protobuf:"varint,17,opt,name=max_run_sec,json=maxRunSec,proto3" json:"max_run_sec,omitempty"`                                                                          // 任务最大允许毫秒数
	GroupName                      string                 `protobuf:"bytes,18,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                                                                             // 分组名称，同组任务会受组的资源限制
	GroupMaxConcur                 uint32                 `protobuf:"varint,19,opt,name=group_max_concur,json=groupMaxConcur,proto3" json:"group_max_concur,omitempty"`                                                           // 每组最大并发
	NextSchedAt                    int64                  `protobuf:"varint,20,opt,name=next_sched_at,json=nextSchedAt,proto3" json:"next_sched_at,omitempty"`                                                                    // 下次调度时间
	TimeCronExpr                   string                 `protobuf:"bytes,21,opt,name=time_cron_expr,json=timeCronExpr,proto3" json:"time_cron_expr,omitempty"`                                                                  // crond表达式，mode为2时有效
	TimeIntervalSec                uint32                 `protobuf:"varint,22,opt,name=time_interval_sec,json=timeIntervalSec,proto3" json:"time_interval_sec,omitempty"`                                                        // 时间间隔，mode为3时有效
	Mode                           int32                  `protobuf:"varint,23,opt,name=mode,proto3" json:"mode,omitempty"`                                                                                                       // 执行模式.1.指定时间戳,2.cron表达式,3.间隔执行
	IsRunInAsync                   int32                  `protobuf:"varint,24,opt,name=is_run_in_async,json=isRunInAsync,proto3" json:"is_run_in_async,omitempty"`                                                               // 是否异步模式运行，0.否，1.是
	LastHeartBeatInAsyncAt         int64                  `protobuf:"varint,25,opt,name=last_heart_beat_in_async_at,json=lastHeartBeatInAsyncAt,proto3" json:"last_heart_beat_in_async_at,omitempty"`                             // 异步运行心跳
	RpcSrv                         string                 `protobuf:"bytes,26,opt,name=rpc_srv,json=rpcSrv,proto3" json:"rpc_srv,omitempty"`                                                                                      // rpc服务
	RpcMethod                      string                 `protobuf:"bytes,27,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpc_method,omitempty"`                                                                             // rpc方法
	Arg                            string                 `protobuf:"bytes,28,opt,name=arg,proto3" json:"arg,omitempty"`                                                                                                          // 任务参数,保存是要更新的内容
	BizId                          string                 `protobuf:"bytes,29,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`                                                                                         // 自定义用于指定任务业务id，由开发人员自己定（不是真的仅仅指账变账单id）
	UniqKey                        string                 `protobuf:"bytes,30,opt,name=uniq_key,json=uniqKey,proto3" json:"uniq_key,omitempty"`                                                                                   // 任务自定义唯一id，该id唯一
	LastErr                        string                 `protobuf:"bytes,31,opt,name=last_err,json=lastErr,proto3" json:"last_err,omitempty"`                                                                                   // 上次错误原因
	LastResExtra                   string                 `protobuf:"bytes,32,opt,name=last_res_extra,json=lastResExtra,proto3" json:"last_res_extra,omitempty"`
	CreatorTrace                   string                 `protobuf:"bytes,33,opt,name=creator_trace,json=creatorTrace,proto3" json:"creator_trace,omitempty"`                  // 创建者trace id
	LastCallbackTrace              string                 `protobuf:"bytes,34,opt,name=last_callback_trace,json=lastCallbackTrace,proto3" json:"last_callback_trace,omitempty"` // 上次回调trace
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_jobsched_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{29}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Job) GetLastSchedAt() int64 {
	if x != nil {
		return x.LastSchedAt
	}
	return 0
}

func (x *Job) GetLastRunAt() int64 {
	if x != nil {
		return x.LastRunAt
	}
	return 0
}

func (x *Job) GetLastFinishRunAt() int64 {
	if x != nil {
		return x.LastFinishRunAt
	}
	return 0
}

func (x *Job) GetLastSuccAt() int64 {
	if x != nil {
		return x.LastSuccAt
	}
	return 0
}

func (x *Job) GetLastFailAt() int64 {
	if x != nil {
		return x.LastFailAt
	}
	return 0
}

func (x *Job) GetSchedCount() uint32 {
	if x != nil {
		return x.SchedCount
	}
	return 0
}

func (x *Job) GetReSchedCountCazTimeout() uint32 {
	if x != nil {
		return x.ReSchedCountCazTimeout
	}
	return 0
}

func (x *Job) GetReRunCountCazFail() uint32 {
	if x != nil {
		return x.ReRunCountCazFail
	}
	return 0
}

func (x *Job) GetRunCount() uint32 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *Job) GetAllowReRunCountCazFailPerSched() uint32 {
	if x != nil {
		return x.AllowReRunCountCazFailPerSched
	}
	return 0
}

func (x *Job) GetReRunCountCazFailCurSched() uint32 {
	if x != nil {
		return x.ReRunCountCazFailCurSched
	}
	return 0
}

func (x *Job) GetSuccCount() uint32 {
	if x != nil {
		return x.SuccCount
	}
	return 0
}

func (x *Job) GetFailCount() uint32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *Job) GetMaxRunSec() uint32 {
	if x != nil {
		return x.MaxRunSec
	}
	return 0
}

func (x *Job) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Job) GetGroupMaxConcur() uint32 {
	if x != nil {
		return x.GroupMaxConcur
	}
	return 0
}

func (x *Job) GetNextSchedAt() int64 {
	if x != nil {
		return x.NextSchedAt
	}
	return 0
}

func (x *Job) GetTimeCronExpr() string {
	if x != nil {
		return x.TimeCronExpr
	}
	return ""
}

func (x *Job) GetTimeIntervalSec() uint32 {
	if x != nil {
		return x.TimeIntervalSec
	}
	return 0
}

func (x *Job) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Job) GetIsRunInAsync() int32 {
	if x != nil {
		return x.IsRunInAsync
	}
	return 0
}

func (x *Job) GetLastHeartBeatInAsyncAt() int64 {
	if x != nil {
		return x.LastHeartBeatInAsyncAt
	}
	return 0
}

func (x *Job) GetRpcSrv() string {
	if x != nil {
		return x.RpcSrv
	}
	return ""
}

func (x *Job) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

func (x *Job) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *Job) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *Job) GetUniqKey() string {
	if x != nil {
		return x.UniqKey
	}
	return ""
}

func (x *Job) GetLastErr() string {
	if x != nil {
		return x.LastErr
	}
	return ""
}

func (x *Job) GetLastResExtra() string {
	if x != nil {
		return x.LastResExtra
	}
	return ""
}

func (x *Job) GetCreatorTrace() string {
	if x != nil {
		return x.CreatorTrace
	}
	return ""
}

func (x *Job) GetLastCallbackTrace() string {
	if x != nil {
		return x.LastCallbackTrace
	}
	return ""
}

type JobGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxConcur     uint32                 `protobuf:"varint,2,opt,name=max_concur,json=maxConcur,proto3" json:"max_concur,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGroup) Reset() {
	*x = JobGroup{}
	mi := &file_jobsched_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGroup) ProtoMessage() {}

func (x *JobGroup) ProtoReflect() protoreflect.Message {
	mi := &file_jobsched_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGroup.ProtoReflect.Descriptor instead.
func (*JobGroup) Descriptor() ([]byte, []int) {
	return file_jobsched_proto_rawDescGZIP(), []int{30}
}

func (x *JobGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobGroup) GetMaxConcur() uint32 {
	if x != nil {
		return x.MaxConcur
	}
	return 0
}

var File_jobsched_proto protoreflect.FileDescriptor

const file_jobsched_proto_rawDesc = "" +
	"\n" +
	"\x0ejobsched.proto\x12\bjobsched\x1a\x0fmgorm_ext.proto\x1a\x13easymicro_ext.proto\"%\n" +
	"\fDeleteJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x0f\n" +
	"\rDeleteJobResp\"\x15\n" +
	"\x13ClearExpiredJobsReq\"\x16\n" +
	"\x14ClearExpiredJobsResp\"\xe0\x03\n" +
	"\tPubJobReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tjob_group\x18\x02 \x01(\tR\bjobGroup\x12/\n" +
	"\x14job_group_max_concur\x18\x03 \x01(\rR\x11jobGroupMaxConcur\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\x12$\n" +
	"\x0etime_cron_expr\x18\x05 \x01(\tR\ftimeCronExpr\x12*\n" +
	"\x11time_interval_sec\x18\x06 \x01(\rR\x0ftimeIntervalSec\x12 \n" +
	"\fspec_time_at\x18\a \x01(\x03R\n" +
	"specTimeAt\x12M\n" +
	"%allow_re_run_count_caz_fail_per_sched\x18\b \x01(\rR\x1eallowReRunCountCazFailPerSched\x12\x17\n" +
	"\arpc_srv\x18\t \x01(\tR\x06rpcSrv\x12\x1d\n" +
	"\n" +
	"rpc_method\x18\n" +
	" \x01(\tR\trpcMethod\x12\x10\n" +
	"\x03arg\x18\v \x01(\tR\x03arg\x12\x15\n" +
	"\x06biz_id\x18\f \x01(\tR\x05bizId\x12\x19\n" +
	"\buniq_key\x18\r \x01(\tR\auniqKey\x12\x1e\n" +
	"\vmax_run_sec\x18\x0e \x01(\rR\tmaxRunSec\"#\n" +
	"\n" +
	"PubJobResp\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xc8\x03\n" +
	"\tSetJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tjob_group\x18\x02 \x01(\tR\bjobGroup\x12/\n" +
	"\x14job_group_max_concur\x18\x03 \x01(\rR\x11jobGroupMaxConcur\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\x12$\n" +
	"\x0etime_cron_expr\x18\x05 \x01(\tR\ftimeCronExpr\x12*\n" +
	"\x11time_interval_sec\x18\x06 \x01(\rR\x0ftimeIntervalSec\x12 \n" +
	"\fspec_time_at\x18\a \x01(\x03R\n" +
	"specTimeAt\x12M\n" +
	"%allow_re_run_count_caz_fail_per_sched\x18\b \x01(\rR\x1eallowReRunCountCazFailPerSched\x12\x17\n" +
	"\arpc_srv\x18\t \x01(\tR\x06rpcSrv\x12\x1d\n" +
	"\n" +
	"rpc_method\x18\n" +
	" \x01(\tR\trpcMethod\x12\x10\n" +
	"\x03arg\x18\v \x01(\tR\x03arg\x12\x1e\n" +
	"\vmax_run_sec\x18\f \x01(\rR\tmaxRunSec\x12\x15\n" +
	"\x06biz_id\x18\r \x01(\tR\x05bizId\"\f\n" +
	"\n" +
	"SetJobResp\"\xb9\x03\n" +
	"\x11SetJobsByBizIdReq\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\x1b\n" +
	"\tjob_group\x18\x02 \x01(\tR\bjobGroup\x12/\n" +
	"\x14job_group_max_concur\x18\x03 \x01(\rR\x11jobGroupMaxConcur\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\x12$\n" +
	"\x0etime_cron_expr\x18\x05 \x01(\tR\ftimeCronExpr\x12*\n" +
	"\x11time_interval_sec\x18\x06 \x01(\rR\x0ftimeIntervalSec\x12 \n" +
	"\fspec_time_at\x18\a \x01(\x03R\n" +
	"specTimeAt\x12M\n" +
	"%allow_re_run_count_caz_fail_per_sched\x18\b \x01(\rR\x1eallowReRunCountCazFailPerSched\x12\x17\n" +
	"\arpc_srv\x18\t \x01(\tR\x06rpcSrv\x12\x1d\n" +
	"\n" +
	"rpc_method\x18\n" +
	" \x01(\tR\trpcMethod\x12\x10\n" +
	"\x03arg\x18\v \x01(\tR\x03arg\x12\x1e\n" +
	"\vmax_run_sec\x18\f \x01(\rR\tmaxRunSec\"/\n" +
	"\x12SetJobsByBizIdResp\x12\x19\n" +
	"\bhas_more\x18\x01 \x01(\bR\ahasMore\"#\n" +
	"\n" +
	"StopJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\r\n" +
	"\vStopJobResp\"0\n" +
	"\x13StopJobByUniqKeyReq\x12\x19\n" +
	"\buniq_key\x18\x01 \x01(\tR\auniqKey\"\x16\n" +
	"\x14StopJobByUniqKeyResp\"+\n" +
	"\x12StopJobsByBizIdReq\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\"0\n" +
	"\x13StopJobsByBizIdResp\x12\x19\n" +
	"\bhas_more\x18\x01 \x01(\bR\ahasMore\"m\n" +
	"\x14HeartBeatAsyncJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06finish\x18\x02 \x01(\bR\x06finish\x12\x14\n" +
	"\x05extra\x18\x03 \x01(\tR\x05extra\x12\x10\n" +
	"\x03err\x18\x04 \x01(\tR\x03err\"\x17\n" +
	"\x15HeartBeatAsyncJobResp\"/\n" +
	"\x12GetJobByUniqKeyReq\x12\x19\n" +
	"\buniq_key\x18\x01 \x01(\tR\auniqKey\"6\n" +
	"\x13GetJobByUniqKeyResp\x12\x1f\n" +
	"\x03job\x18\x01 \x01(\v2\r.jobsched.JobR\x03job\"v\n" +
	"\x11GetJobsByBizIdReq\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.jobsched.PageR\x04page\x12&\n" +
	"\x0fneed_calc_total\x18\x03 \x01(\bR\rneedCalcTotal\"q\n" +
	"\x12GetJobsByBizIdResp\x12!\n" +
	"\x04jobs\x18\x01 \x03(\v2\r.jobsched.JobR\x04jobs\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.jobsched.PageR\x04page\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\"\"\n" +
	"\tGetJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"-\n" +
	"\n" +
	"GetJobResp\x12\x1f\n" +
	"\x03job\x18\x01 \x01(\v2\r.jobsched.JobR\x03job\"\"\n" +
	"\tDelJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\f\n" +
	"\n" +
	"DelJobResp\"/\n" +
	"\x12DelJobByUniqKeyReq\x12\x19\n" +
	"\buniq_key\x18\x01 \x01(\tR\auniqKey\"\x15\n" +
	"\x13DelJobByUniqKeyResp\".\n" +
	"\x04Page\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\xa1\n" +
	"\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\"\n" +
	"\rlast_sched_at\x18\x04 \x01(\x03R\vlastSchedAt\x12\x1e\n" +
	"\vlast_run_at\x18\x05 \x01(\x03R\tlastRunAt\x12+\n" +
	"\x12last_finish_run_at\x18\x06 \x01(\x03R\x0flastFinishRunAt\x12 \n" +
	"\flast_succ_at\x18\a \x01(\x03R\n" +
	"lastSuccAt\x12 \n" +
	"\flast_fail_at\x18\b \x01(\x03R\n" +
	"lastFailAt\x12\x1f\n" +
	"\vsched_count\x18\t \x01(\rR\n" +
	"schedCount\x12:\n" +
	"\x1are_sched_count_caz_timeout\x18\n" +
	" \x01(\rR\x16reSchedCountCazTimeout\x120\n" +
	"\x15re_run_count_caz_fail\x18\v \x01(\rR\x11reRunCountCazFail\x12\x1b\n" +
	"\trun_count\x18\f \x01(\rR\brunCount\x12M\n" +
	"%allow_re_run_count_caz_fail_per_sched\x18\r \x01(\rR\x1eallowReRunCountCazFailPerSched\x12B\n" +
	"\x1fre_run_count_caz_fail_cur_sched\x18\x0e \x01(\rR\x19reRunCountCazFailCurSched\x12\x1d\n" +
	"\n" +
	"succ_count\x18\x0f \x01(\rR\tsuccCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x10 \x01(\rR\tfailCount\x12\x1e\n" +
	"\vmax_run_sec\x18\x11 \x01(\rR\tmaxRunSec\x12\x1d\n" +
	"\n" +
	"group_name\x18\x12 \x01(\tR\tgroupName\x12(\n" +
	"\x10group_max_concur\x18\x13 \x01(\rR\x0egroupMaxConcur\x12\"\n" +
	"\rnext_sched_at\x18\x14 \x01(\x03R\vnextSchedAt\x12$\n" +
	"\x0etime_cron_expr\x18\x15 \x01(\tR\ftimeCronExpr\x12*\n" +
	"\x11time_interval_sec\x18\x16 \x01(\rR\x0ftimeIntervalSec\x12\x12\n" +
	"\x04mode\x18\x17 \x01(\x05R\x04mode\x12%\n" +
	"\x0fis_run_in_async\x18\x18 \x01(\x05R\fisRunInAsync\x12;\n" +
	"\x1blast_heart_beat_in_async_at\x18\x19 \x01(\x03R\x16lastHeartBeatInAsyncAt\x12\x17\n" +
	"\arpc_srv\x18\x1a \x01(\tR\x06rpcSrv\x12\x1d\n" +
	"\n" +
	"rpc_method\x18\x1b \x01(\tR\trpcMethod\x12\x10\n" +
	"\x03arg\x18\x1c \x01(\tR\x03arg\x12\x15\n" +
	"\x06biz_id\x18\x1d \x01(\tR\x05bizId\x12\x19\n" +
	"\buniq_key\x18\x1e \x01(\tR\auniqKey\x12\x19\n" +
	"\blast_err\x18\x1f \x01(\tR\alastErr\x12$\n" +
	"\x0elast_res_extra\x18  \x01(\tR\flastResExtra\x12#\n" +
	"\rcreator_trace\x18! \x01(\tR\fcreatorTrace\x12.\n" +
	"\x13last_callback_trace\x18\" \x01(\tR\x11lastCallbackTrace:<\x8a\x8e%8\n" +
	"\feasymicrojob\x12\feasymicrojob\x1a\x03job*\x06biz_id*\buniq_keyP\x01\x90\x01\x01\"u\n" +
	"\bJobGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"max_concur\x18\x02 \x01(\rR\tmaxConcur:6\x8a\x8e%2\n" +
	"\feasymicrojob\x12\feasymicrojob\x1a\tjob_group:\x04nameP\x01\x90\x01\x01*x\n" +
	"\fSchedJobMode\x12\x13\n" +
	"\x0fSchedJobModeNil\x10\x00\x12\x18\n" +
	"\x14SchedJobModeSpecTime\x10\x01\x12\x18\n" +
	"\x14SchedJobModeTimeCron\x10\x02\x12\x1f\n" +
	"\x1bSchedJobModeTimeIntervalSec\x10\x03*L\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12\x18\n" +
	"\x13ErrCodeParamInvalid\x10\x89'\x12\x17\n" +
	"\x12ErrCodeJobNotFound\x10\x8a'*\xc8\x01\n" +
	"\x0eSchedJobStatus\x12\x15\n" +
	"\x11SchedJobStatusNil\x10\x00\x12\x17\n" +
	"\x13SchedJobStatusSched\x10\x01\x12\x19\n" +
	"\x15SchedJobStatusRunning\x10\x02\x12\x18\n" +
	"\x14SchedJobStatusFinish\x10\x03\x12\x19\n" +
	"\x15SchedJobStatusStopped\x10\x04\x12\x1e\n" +
	"\x1aSchedJobStatusRunningAsync\x10\x05\x12\x16\n" +
	"\x12SchedJobStatusFail\x10\x062\xdb\x06\n" +
	"\bJobSched\x123\n" +
	"\x06PubJob\x12\x13.jobsched.PubJobReq\x1a\x14.jobsched.PubJobResp\x123\n" +
	"\x06SetJob\x12\x13.jobsched.SetJobReq\x1a\x14.jobsched.SetJobResp\x12K\n" +
	"\x0eSetJobsByBizId\x12\x1b.jobsched.SetJobsByBizIdReq\x1a\x1c.jobsched.SetJobsByBizIdResp\x126\n" +
	"\aStopJob\x12\x14.jobsched.StopJobReq\x1a\x15.jobsched.StopJobResp\x12Q\n" +
	"\x10StopJobByUniqKey\x12\x1d.jobsched.StopJobByUniqKeyReq\x1a\x1e.jobsched.StopJobByUniqKeyResp\x12N\n" +
	"\x0fStopJobsByBizId\x12\x1c.jobsched.StopJobsByBizIdReq\x1a\x1d.jobsched.StopJobsByBizIdResp\x123\n" +
	"\x06GetJob\x12\x13.jobsched.GetJobReq\x1a\x14.jobsched.GetJobResp\x12K\n" +
	"\x0eGetJobsByBizId\x12\x1b.jobsched.GetJobsByBizIdReq\x1a\x1c.jobsched.GetJobsByBizIdResp\x12N\n" +
	"\x0fGetJobByUniqKey\x12\x1c.jobsched.GetJobByUniqKeyReq\x1a\x1d.jobsched.GetJobByUniqKeyResp\x12T\n" +
	"\x11HeartBeatAsyncJob\x12\x1e.jobsched.HeartBeatAsyncJobReq\x1a\x1f.jobsched.HeartBeatAsyncJobResp\x12W\n" +
	"\x10ClearExpiredJobs\x12\x1d.jobsched.ClearExpiredJobsReq\x1a\x1e.jobsched.ClearExpiredJobsResp\"\x04\x8a\x9d \x00\x12<\n" +
	"\tDeleteJob\x12\x16.jobsched.DeleteJobReq\x1a\x17.jobsched.DeleteJobRespB\\\x8a\x9d \x1cZ\feasymicrojobb\feasymicrojobZ:github.com/995933447/easymicro/grpc/middleservice/jobschedb\x06proto3"

var (
	file_jobsched_proto_rawDescOnce sync.Once
	file_jobsched_proto_rawDescData []byte
)

func file_jobsched_proto_rawDescGZIP() []byte {
	file_jobsched_proto_rawDescOnce.Do(func() {
		file_jobsched_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobsched_proto_rawDesc), len(file_jobsched_proto_rawDesc)))
	})
	return file_jobsched_proto_rawDescData
}

var file_jobsched_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_jobsched_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_jobsched_proto_goTypes = []any{
	(SchedJobMode)(0),             // 0: jobsched.SchedJobMode
	(ErrCode)(0),                  // 1: jobsched.ErrCode
	(SchedJobStatus)(0),           // 2: jobsched.SchedJobStatus
	(*DeleteJobReq)(nil),          // 3: jobsched.DeleteJobReq
	(*DeleteJobResp)(nil),         // 4: jobsched.DeleteJobResp
	(*ClearExpiredJobsReq)(nil),   // 5: jobsched.ClearExpiredJobsReq
	(*ClearExpiredJobsResp)(nil),  // 6: jobsched.ClearExpiredJobsResp
	(*PubJobReq)(nil),             // 7: jobsched.PubJobReq
	(*PubJobResp)(nil),            // 8: jobsched.PubJobResp
	(*SetJobReq)(nil),             // 9: jobsched.SetJobReq
	(*SetJobResp)(nil),            // 10: jobsched.SetJobResp
	(*SetJobsByBizIdReq)(nil),     // 11: jobsched.SetJobsByBizIdReq
	(*SetJobsByBizIdResp)(nil),    // 12: jobsched.SetJobsByBizIdResp
	(*StopJobReq)(nil),            // 13: jobsched.StopJobReq
	(*StopJobResp)(nil),           // 14: jobsched.StopJobResp
	(*StopJobByUniqKeyReq)(nil),   // 15: jobsched.StopJobByUniqKeyReq
	(*StopJobByUniqKeyResp)(nil),  // 16: jobsched.StopJobByUniqKeyResp
	(*StopJobsByBizIdReq)(nil),    // 17: jobsched.StopJobsByBizIdReq
	(*StopJobsByBizIdResp)(nil),   // 18: jobsched.StopJobsByBizIdResp
	(*HeartBeatAsyncJobReq)(nil),  // 19: jobsched.HeartBeatAsyncJobReq
	(*HeartBeatAsyncJobResp)(nil), // 20: jobsched.HeartBeatAsyncJobResp
	(*GetJobByUniqKeyReq)(nil),    // 21: jobsched.GetJobByUniqKeyReq
	(*GetJobByUniqKeyResp)(nil),   // 22: jobsched.GetJobByUniqKeyResp
	(*GetJobsByBizIdReq)(nil),     // 23: jobsched.GetJobsByBizIdReq
	(*GetJobsByBizIdResp)(nil),    // 24: jobsched.GetJobsByBizIdResp
	(*GetJobReq)(nil),             // 25: jobsched.GetJobReq
	(*GetJobResp)(nil),            // 26: jobsched.GetJobResp
	(*DelJobReq)(nil),             // 27: jobsched.DelJobReq
	(*DelJobResp)(nil),            // 28: jobsched.DelJobResp
	(*DelJobByUniqKeyReq)(nil),    // 29: jobsched.DelJobByUniqKeyReq
	(*DelJobByUniqKeyResp)(nil),   // 30: jobsched.DelJobByUniqKeyResp
	(*Page)(nil),                  // 31: jobsched.Page
	(*Job)(nil),                   // 32: jobsched.Job
	(*JobGroup)(nil),              // 33: jobsched.JobGroup
}
var file_jobsched_proto_depIdxs = []int32{
	32, // 0: jobsched.GetJobByUniqKeyResp.job:type_name -> jobsched.Job
	31, // 1: jobsched.GetJobsByBizIdReq.page:type_name -> jobsched.Page
	32, // 2: jobsched.GetJobsByBizIdResp.jobs:type_name -> jobsched.Job
	31, // 3: jobsched.GetJobsByBizIdResp.page:type_name -> jobsched.Page
	32, // 4: jobsched.GetJobResp.job:type_name -> jobsched.Job
	7,  // 5: jobsched.JobSched.PubJob:input_type -> jobsched.PubJobReq
	9,  // 6: jobsched.JobSched.SetJob:input_type -> jobsched.SetJobReq
	11, // 7: jobsched.JobSched.SetJobsByBizId:input_type -> jobsched.SetJobsByBizIdReq
	13, // 8: jobsched.JobSched.StopJob:input_type -> jobsched.StopJobReq
	15, // 9: jobsched.JobSched.StopJobByUniqKey:input_type -> jobsched.StopJobByUniqKeyReq
	17, // 10: jobsched.JobSched.StopJobsByBizId:input_type -> jobsched.StopJobsByBizIdReq
	25, // 11: jobsched.JobSched.GetJob:input_type -> jobsched.GetJobReq
	23, // 12: jobsched.JobSched.GetJobsByBizId:input_type -> jobsched.GetJobsByBizIdReq
	21, // 13: jobsched.JobSched.GetJobByUniqKey:input_type -> jobsched.GetJobByUniqKeyReq
	19, // 14: jobsched.JobSched.HeartBeatAsyncJob:input_type -> jobsched.HeartBeatAsyncJobReq
	5,  // 15: jobsched.JobSched.ClearExpiredJobs:input_type -> jobsched.ClearExpiredJobsReq
	3,  // 16: jobsched.JobSched.DeleteJob:input_type -> jobsched.DeleteJobReq
	8,  // 17: jobsched.JobSched.PubJob:output_type -> jobsched.PubJobResp
	10, // 18: jobsched.JobSched.SetJob:output_type -> jobsched.SetJobResp
	12, // 19: jobsched.JobSched.SetJobsByBizId:output_type -> jobsched.SetJobsByBizIdResp
	14, // 20: jobsched.JobSched.StopJob:output_type -> jobsched.StopJobResp
	16, // 21: jobsched.JobSched.StopJobByUniqKey:output_type -> jobsched.StopJobByUniqKeyResp
	18, // 22: jobsched.JobSched.StopJobsByBizId:output_type -> jobsched.StopJobsByBizIdResp
	26, // 23: jobsched.JobSched.GetJob:output_type -> jobsched.GetJobResp
	24, // 24: jobsched.JobSched.GetJobsByBizId:output_type -> jobsched.GetJobsByBizIdResp
	22, // 25: jobsched.JobSched.GetJobByUniqKey:output_type -> jobsched.GetJobByUniqKeyResp
	20, // 26: jobsched.JobSched.HeartBeatAsyncJob:output_type -> jobsched.HeartBeatAsyncJobResp
	6,  // 27: jobsched.JobSched.ClearExpiredJobs:output_type -> jobsched.ClearExpiredJobsResp
	4,  // 28: jobsched.JobSched.DeleteJob:output_type -> jobsched.DeleteJobResp
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_jobsched_proto_init() }
func file_jobsched_proto_init() {
	if File_jobsched_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobsched_proto_rawDesc), len(file_jobsched_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobsched_proto_goTypes,
		DependencyIndexes: file_jobsched_proto_depIdxs,
		EnumInfos:         file_jobsched_proto_enumTypes,
		MessageInfos:      file_jobsched_proto_msgTypes,
	}.Build()
	File_jobsched_proto = out.File
	file_jobsched_proto_goTypes = nil
	file_jobsched_proto_depIdxs = nil
}
