// Code generated by protoc-gen-mgorm. DO NOT EDIT.
package echo

import (
	"context"
	"fmt"
	"time"
	"math/rand"

	"github.com/995933447/mgorm"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

const (
	EchoerDbName   = "echo_%d"
	EchoerTbName   = "echoer"
	EchoerConnName = "default"

	EchoerTtlSec = 3 * 24 * 3600
)

// 索引
var echoerIndexKeys = []string{}

var echoerUniqueIndexKeys = []string{
	"echoer_name",
}

var echoerExpireIndexKeys = []string{
	"expire_at",
}

type EchoerOrm struct {
	ID         primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`
	EchoerName string             `json:"echoer_name" bson:"echoer_name"`
	CreatedAt  time.Time          `json:"created_at,omitempty" bson:"created_at,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at,omitempty" bson:"updated_at,omitempty"`
	ExpireAt   time.Time          `json:"expire_at,omitempty" bson:"expire_at,omitempty"`
}

var echoerOrmCache mgorm.Cache

func SetEchoerOrmCache(cache mgorm.Cache) {
	echoerOrmCache = cache
}

var onEchoerOrmQueryDone mgorm.OnQueryDoneFunc

func SetEchoerOrmOnQueryDone(fn mgorm.OnQueryDoneFunc) {
	onEchoerOrmQueryDone = fn
}

func NewEchoerModel(dbIdx int64) *EchoerModel {
	cache := echoerOrmCache
	if cache == nil {
		cache = mgorm.DefaultCache
	}
	orm := mgorm.NewOrm(
		EchoerConnName,
		fmt.Sprintf(EchoerDbName, dbIdx),
		EchoerTbName,
		true,
		cache,
		echoerIndexKeys,
		echoerUniqueIndexKeys,
		echoerExpireIndexKeys,
	)
	onQueryDoneFunc := onEchoerOrmQueryDone
	if onQueryDoneFunc == nil {
		onQueryDoneFunc = mgorm.OnQueryDone
	}
	orm.SetOnQueryDone(onQueryDoneFunc)
	return &EchoerModel{
		Model: mgorm.Model[EchoerOrm]{
			Orm:    orm,
			Cached: true,
		},
	}
}

type EchoerModel struct {
	mgorm.Model[EchoerOrm]
}

func (m *EchoerModel) NormalizeOrmForInsert(data *EchoerOrm) {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = data.CreatedAt
	if data.ExpireAt.IsZero() {
		r := rand.New(rand.NewSource(time.Now().UnixNano()))
		data.ExpireAt = time.Now().Add((EchoerTtlSec + time.Duration(r.Int63n(10800))) * time.Second)
	}
}

func (m *EchoerModel) InsertOneIgnoreConflict(ctx context.Context, data *EchoerOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOneIgnoreConflict(ctx, data)
	return err
}

func (m *EchoerModel) InsertOne(ctx context.Context, data *EchoerOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOne(ctx, data)
	return err
}

func (m *EchoerModel) InsertMany(ctx context.Context, dataList []*EchoerOrm) error {
	var ins []any
	for _, data := range dataList {
		m.NormalizeOrmForInsert(data)
		ins = append(ins, data)
	}
	_, err := m.Model.InsertMany(ctx, ins)
	return err
}

func (m *EchoerModel) GetCacheKeys(data *EchoerOrm) []string {
	var cacheKeys []string
	cacheKeys = append(cacheKeys, fmt.Sprintf("_id:%s", data.ID.Hex()))
	cacheKeys = append(cacheKeys, fmt.Sprintf(
		"echoer_name:%s", data.EchoerName,
	))
	return cacheKeys
}

func (m *EchoerModel) Update(ctx context.Context, data *EchoerOrm) (*mongo.UpdateResult, error) {
	dataB, err := mgorm.ToBsonM(data)
	if err != nil {
		return nil, err
	}
	old, err := m.Model.FindOneByID(ctx, data.ID.Hex())
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}
	dataB["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": dataB["_id"]}, bson.M{"$set": dataB})
}

func (m *EchoerModel) UpdateOne(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	old, err := m.Model.FindOne(ctx, filter)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": data})
}

func (m *EchoerModel) UpdateMany(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	list, err := m.Model.FindAll(ctx, filter)
	if err != nil {
		return nil, err
	}
	if len(list) > 0 {
		var cacheKeys []string
		for _, item := range list {
			cacheKeys = append(cacheKeys, m.GetCacheKeys(item)...)
		}
		defer m.Model.DelCache(cacheKeys)
	}
	data["updated_at"] = time.Now()
	return m.Model.UpdateMany(ctx, filter, bson.M{"$set": data})
}

func (m *EchoerModel) Upsert(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()
	old, err := m.Model.FindOne(ctx, filter)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$setOnInsert": insertData})
}

func (m *EchoerModel) UpInc(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	insertData["created_at"] = time.Now()
	old, err := m.Model.FindOne(ctx, filter)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}

	return m.Model.Upsert(ctx, filter, bson.M{"$inc": data, "$set": bson.M{"updated_at": time.Now()}, "$setOnInsert": insertData})
}

func (m *EchoerModel) UpAndInc(ctx context.Context, filter any, data, incdata bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()
	old, err := m.Model.FindOne(ctx, filter)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$inc": incdata, "$setOnInsert": insertData})
}

func (m *EchoerModel) DeleteOne(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	old, err := m.Model.FindOne(ctx, filter)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}
	return m.Model.DeleteOne(ctx, filter)
}

func (m *EchoerModel) DeleteMany(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	list, err := m.Model.FindAll(ctx, filter)
	if err != nil {
		return nil, err
	}
	if len(list) > 0 {
		var cacheKeys []string
		for _, item := range list {
			cacheKeys = append(cacheKeys, m.GetCacheKeys(item)...)
		}
		defer m.Model.DelCache(cacheKeys)
	}
	return m.Model.DeleteMany(ctx, filter)
}

func (m *EchoerModel) UpdateOneByID(ctx context.Context, id string, data bson.M) (*mongo.UpdateResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	old, err := m.Model.FindOneByID(ctx, id)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": objId}, bson.M{"$set": data})
}

func (m *EchoerModel) DeleteOneByID(ctx context.Context, id string) (*mongo.DeleteResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	old, err := m.Model.FindOneByID(ctx, id)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(old))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}

	return m.Model.DeleteOne(ctx, bson.M{"_id": objId})
}

func (m *EchoerModel) FindOneByID(ctx context.Context, id string) (*EchoerOrm, error) {
	var data EchoerOrm
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	filter := bson.M{"_id": objId}
	cacheKey := fmt.Sprintf("_id:%s", id)
	err = m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (m *EchoerModel) UpdateOneByEchoerName(ctx context.Context, echoerName string, update bson.M) (*mongo.UpdateResult, error) {
	filter := bson.M{}
	var data EchoerOrm
	filter["echoer_name"] = echoerName
	cacheKey := fmt.Sprintf(
		"echoer_name:%s",
		echoerName,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(&data))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}

	update["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": update})
}

func (m *EchoerModel) FindOneByEchoerName(ctx context.Context, echoerName string) (*EchoerOrm, error) {
	var data EchoerOrm
	filter := bson.M{}
	filter["echoer_name"] = echoerName
	cacheKey := fmt.Sprintf(
		"echoer_name:%s",
		echoerName,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (m *EchoerModel) DeleteOneByEchoerName(ctx context.Context, echoerName string) (*mongo.DeleteResult, error) {
	var data EchoerOrm
	filter := bson.M{}
	filter["echoer_name"] = echoerName
	cacheKey := fmt.Sprintf(
		"echoer_name:%s",
		echoerName,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(&data))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}
	return m.Model.DeleteOne(ctx, filter)
}
