// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: echo.proto

package echo

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Nil     ErrCode = 0
	ErrCode_ErrFail ErrCode = 1001
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "Nil",
		1001: "ErrFail",
	}
	ErrCode_value = map[string]int32{
		"Nil":     0,
		"ErrFail": 1001,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_echo_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_echo_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{0}
}

type EchoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Echo          string                 `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoReq) Reset() {
	*x = EchoReq{}
	mi := &file_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReq) ProtoMessage() {}

func (x *EchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReq.ProtoReflect.Descriptor instead.
func (*EchoReq) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoReq) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

func (x *EchoReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *EchoReq) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type EchoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Echo          string                 `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResp) Reset() {
	*x = EchoResp{}
	mi := &file_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResp) ProtoMessage() {}

func (x *EchoResp) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResp.ProtoReflect.Descriptor instead.
func (*EchoResp) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResp) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

type Echoer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EchoerName    string                 `protobuf:"bytes,1,opt,name=echoer_name,json=echoerName,proto3" json:"echoer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echoer) Reset() {
	*x = Echoer{}
	mi := &file_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echoer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echoer) ProtoMessage() {}

func (x *Echoer) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echoer.ProtoReflect.Descriptor instead.
func (*Echoer) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{2}
}

func (x *Echoer) GetEchoerName() string {
	if x != nil {
		return x.EchoerName
	}
	return ""
}

type StopJobByUniqKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqKey       string                 `protobuf:"bytes,1,opt,name=uniq_key,json=uniqKey,proto3" json:"uniq_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobByUniqKeyReq) Reset() {
	*x = StopJobByUniqKeyReq{}
	mi := &file_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobByUniqKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobByUniqKeyReq) ProtoMessage() {}

func (x *StopJobByUniqKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobByUniqKeyReq.ProtoReflect.Descriptor instead.
func (*StopJobByUniqKeyReq) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{3}
}

func (x *StopJobByUniqKeyReq) GetUniqKey() string {
	if x != nil {
		return x.UniqKey
	}
	return ""
}

type StopJobByUniqKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobByUniqKeyResp) Reset() {
	*x = StopJobByUniqKeyResp{}
	mi := &file_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobByUniqKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobByUniqKeyResp) ProtoMessage() {}

func (x *StopJobByUniqKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobByUniqKeyResp.ProtoReflect.Descriptor instead.
func (*StopJobByUniqKeyResp) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{4}
}

var File_echo_proto protoreflect.FileDescriptor

const file_echo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"echo.proto\x12\x04echo\x1a\x0fmgorm_ext.proto\x1a\x13easymicro_ext.proto\"V\n" +
	"\aEchoReq\x12\x12\n" +
	"\x04echo\x18\x01 \x01(\tR\x04echo\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\"\x1e\n" +
	"\bEchoResp\x12\x12\n" +
	"\x04echo\x18\x01 \x01(\tR\x04echo\"Z\n" +
	"\x06Echoer\x12\x1f\n" +
	"\vechoer_name\x18\x01 \x01(\tR\n" +
	"echoerName:/\x8a\x8e%+\n" +
	"\adefault\x12\aecho_%d\x1a\x06echoer \x01:\vechoer_nameh\x03\"0\n" +
	"\x13StopJobByUniqKeyReq\x12\x19\n" +
	"\buniq_key\x18\x01 \x01(\tR\auniqKey\"\x16\n" +
	"\x14StopJobByUniqKeyResp* \n" +
	"\aErrCode\x12\a\n" +
	"\x03Nil\x10\x00\x12\f\n" +
	"\aErrFail\x10\xe9\a2j\n" +
	"\x04Echo\x120\n" +
	"\tBasicEcho\x12\r.echo.EchoReq\x1a\x0e.echo.EchoResp\"\x04\x8a\x9d \x00\x120\n" +
	"\tProxyEcho\x12\r.echo.EchoReq\x1a\x0e.echo.EchoResp\"\x04\x8a\x9d \x00B-Z+github.com/995933447/easymicro/example/echob\x06proto3"

var (
	file_echo_proto_rawDescOnce sync.Once
	file_echo_proto_rawDescData []byte
)

func file_echo_proto_rawDescGZIP() []byte {
	file_echo_proto_rawDescOnce.Do(func() {
		file_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)))
	})
	return file_echo_proto_rawDescData
}

var file_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_echo_proto_goTypes = []any{
	(ErrCode)(0),                 // 0: echo.ErrCode
	(*EchoReq)(nil),              // 1: echo.EchoReq
	(*EchoResp)(nil),             // 2: echo.EchoResp
	(*Echoer)(nil),               // 3: echo.Echoer
	(*StopJobByUniqKeyReq)(nil),  // 4: echo.StopJobByUniqKeyReq
	(*StopJobByUniqKeyResp)(nil), // 5: echo.StopJobByUniqKeyResp
}
var file_echo_proto_depIdxs = []int32{
	1, // 0: echo.Echo.BasicEcho:input_type -> echo.EchoReq
	1, // 1: echo.Echo.ProxyEcho:input_type -> echo.EchoReq
	2, // 2: echo.Echo.BasicEcho:output_type -> echo.EchoResp
	2, // 3: echo.Echo.ProxyEcho:output_type -> echo.EchoResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_proto_init() }
func file_echo_proto_init() {
	if File_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_proto_goTypes,
		DependencyIndexes: file_echo_proto_depIdxs,
		EnumInfos:         file_echo_proto_enumTypes,
		MessageInfos:      file_echo_proto_msgTypes,
	}.Build()
	File_echo_proto = out.File
	file_echo_proto_goTypes = nil
	file_echo_proto_depIdxs = nil
}
