// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package echo

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "easymicro"
	EasymicroDiscoveryName = "default"
)

const EasymicroGRPCPbServiceNameEcho = "echo.Echo"

var EchoDefault = &Echo{}

func EchoGRPC() *Echo {
	return EchoDefault
}

func NewEchoGRPC(dialOpts ...grpc.DialOption) *Echo {
	return &Echo{
		dialOpts: dialOpts,
	}
}

type Echo struct {
	c        EchoClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *Echo) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *Echo) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameEcho)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameEcho, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewEchoClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *Echo) BasicEcho(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.BasicEcho(ctx, in, opts...)
}

func (s *Echo) ProxyEcho(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ProxyEcho(ctx, in, opts...)
}
