// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/example/corp"
	"github.com/995933447/easymicro/example/corpserver/handler"
	"github.com/995933447/easymicro/nats"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(corp.EasymicroGRPCPbServiceNameCorp, "GetCorp", handler.CorpHandler.GetCorp, func() *corp.GetCorpReq {
		return &corp.GetCorpReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
