// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/example/corp"
	"github.com/995933447/easymicro/example/corpserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	corp.EasymicroGRPCPbServiceNameCorp,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	corp.RegisterCorpServer(server, handler.CorpHandler)
	return nil
}
