// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: easymicro_ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrMessage) Reset() {
	*x = ErrMessage{}
	mi := &file_easymicro_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrMessage) ProtoMessage() {}

func (x *ErrMessage) ProtoReflect() protoreflect.Message {
	mi := &file_easymicro_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrMessage.ProtoReflect.Descriptor instead.
func (*ErrMessage) Descriptor() ([]byte, []int) {
	return file_easymicro_ext_proto_rawDescGZIP(), []int{0}
}

func (x *ErrMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobOpts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobOpts) Reset() {
	*x = JobOpts{}
	mi := &file_easymicro_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOpts) ProtoMessage() {}

func (x *JobOpts) ProtoReflect() protoreflect.Message {
	mi := &file_easymicro_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOpts.ProtoReflect.Descriptor instead.
func (*JobOpts) Descriptor() ([]byte, []int) {
	return file_easymicro_ext_proto_rawDescGZIP(), []int{1}
}

type JsonSchemaOutputOpts struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	EnabledReference                  bool                   `protobuf:"varint,1,opt,name=enabled_reference,json=enabledReference,proto3" json:"enabled_reference,omitempty"`                                                            // 设置为true则github.com/invopop/jsonschema.DoNotReference为false,默认DoNotReference为true
	DisabledAdditionalProperties      bool                   `protobuf:"varint,2,opt,name=disabled_additional_properties,json=disabledAdditionalProperties,proto3" json:"disabled_additional_properties,omitempty"`                      // 设置为true则github.com/invopop/jsonschema.AllowAdditionalProperties为false,默认为true
	DisabledRequireFromJsonSchemaTags bool                   `protobuf:"varint,3,opt,name=disabled_require_from_json_schema_tags,json=disabledRequireFromJsonSchemaTags,proto3" json:"disabled_require_from_json_schema_tags,omitempty"` // 设置为true则github.com/invopop/jsonschema.RequiredFromJSONSchemaTags为false,默认为true
	FieldNameTag                      string                 `protobuf:"bytes,4,opt,name=field_name_tag,json=fieldNameTag,proto3" json:"field_name_tag,omitempty"`                                                                       // 设置github.com/invopop/jsonschema.FieldNameTag
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *JsonSchemaOutputOpts) Reset() {
	*x = JsonSchemaOutputOpts{}
	mi := &file_easymicro_ext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonSchemaOutputOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonSchemaOutputOpts) ProtoMessage() {}

func (x *JsonSchemaOutputOpts) ProtoReflect() protoreflect.Message {
	mi := &file_easymicro_ext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonSchemaOutputOpts.ProtoReflect.Descriptor instead.
func (*JsonSchemaOutputOpts) Descriptor() ([]byte, []int) {
	return file_easymicro_ext_proto_rawDescGZIP(), []int{2}
}

func (x *JsonSchemaOutputOpts) GetEnabledReference() bool {
	if x != nil {
		return x.EnabledReference
	}
	return false
}

func (x *JsonSchemaOutputOpts) GetDisabledAdditionalProperties() bool {
	if x != nil {
		return x.DisabledAdditionalProperties
	}
	return false
}

func (x *JsonSchemaOutputOpts) GetDisabledRequireFromJsonSchemaTags() bool {
	if x != nil {
		return x.DisabledRequireFromJsonSchemaTags
	}
	return false
}

func (x *JsonSchemaOutputOpts) GetFieldNameTag() string {
	if x != nil {
		return x.FieldNameTag
	}
	return ""
}

type ProtoGenOpts struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ServerPackage               string                 `protobuf:"bytes,1,opt,name=server_package,json=serverPackage,proto3" json:"server_package,omitempty"`                                                   // 服务端包名，不指定则使用go_option报名加server后缀作为默认包名
	DisabledLoadFastlog         bool                   `protobuf:"varint,2,opt,name=disabled_load_fastlog,json=disabledLoadFastlog,proto3" json:"disabled_load_fastlog,omitempty"`                              // 是否禁用生成自动从本地加载fastlog
	DisabledLoadMongo           bool                   `protobuf:"varint,3,opt,name=disabled_load_mongo,json=disabledLoadMongo,proto3" json:"disabled_load_mongo,omitempty"`                                    // 是否禁用生成自动从本地加载mongo
	DisabledLoadRedis           bool                   `protobuf:"varint,4,opt,name=disabled_load_redis,json=disabledLoadRedis,proto3" json:"disabled_load_redis,omitempty"`                                    // 是否禁用生成自动从本地加载redis
	DisabledLoadEtcd            bool                   `protobuf:"varint,5,opt,name=disabled_load_etcd,json=disabledLoadEtcd,proto3" json:"disabled_load_etcd,omitempty"`                                       // 是否禁用生成自动从本地加载etcd
	DisabledLoadDiscovery       bool                   `protobuf:"varint,6,opt,name=disabled_load_discovery,json=disabledLoadDiscovery,proto3" json:"disabled_load_discovery,omitempty"`                        // 是否禁用生成自动从本地加载默认的服务发现
	DisabledLoadNats            bool                   `protobuf:"varint,7,opt,name=disabled_load_nats,json=disabledLoadNats,proto3" json:"disabled_load_nats,omitempty"`                                       // 是否禁用生成自动从本地加载nats
	DisabledElect               bool                   `protobuf:"varint,8,opt,name=disabled_elect,json=disabledElect,proto3" json:"disabled_elect,omitempty"`                                                  // 是否禁用自动选举
	ElectDriverName             string                 `protobuf:"bytes,9,opt,name=elect_driver_name,json=electDriverName,proto3" json:"elect_driver_name,omitempty"`                                           // 选举器使用的驱动名称
	ElectDriverConn             string                 `protobuf:"bytes,10,opt,name=elect_driver_conn,json=electDriverConn,proto3" json:"elect_driver_conn,omitempty"`                                          // 选举器使用的驱动连接
	GrpcSchema                  string                 `protobuf:"bytes,11,opt,name=grpc_schema,json=grpcSchema,proto3" json:"grpc_schema,omitempty"`                                                           // 指定grpc解析器协议, 默认是easymicro
	DiscoveryName               string                 `protobuf:"bytes,12,opt,name=discovery_name,json=discoveryName,proto3" json:"discovery_name,omitempty"`                                                  // 指定服务发现，默认是default
	EnabledHealth               bool                   `protobuf:"varint,13,opt,name=enabled_health,json=enabledHealth,proto3" json:"enabled_health,omitempty"`                                                 // 是否启用easymicro内置的服务健康检查
	AutoGoModClient             bool                   `protobuf:"varint,14,opt,name=auto_go_mod_client,json=autoGoModClient,proto3" json:"auto_go_mod_client,omitempty"`                                       // 是否在客户端输出代码目录下自动生go.mod
	AutoGoModServer             bool                   `protobuf:"varint,15,opt,name=auto_go_mod_server,json=autoGoModServer,proto3" json:"auto_go_mod_server,omitempty"`                                       // 是否自动服务端输出代码目录下自动生成go.mod
	MgormRedisCacheConn         string                 `protobuf:"bytes,16,opt,name=mgorm_redis_cache_conn,json=mgormRedisCacheConn,proto3" json:"mgorm_redis_cache_conn,omitempty"`                            // mgorm redis 缓存 的Redis 连接名称
	DisabledMgormRedisCacheConn bool                   `protobuf:"varint,17,opt,name=disabled_mgorm_redis_cache_conn,json=disabledMgormRedisCacheConn,proto3" json:"disabled_mgorm_redis_cache_conn,omitempty"` // 是否禁用 mgorm Redis 缓存
	DisabledFastlogMgormQuery   bool                   `protobuf:"varint,18,opt,name=disabled_fastlog_mgorm_query,json=disabledFastlogMgormQuery,proto3" json:"disabled_fastlog_mgorm_query,omitempty"`         // 是否禁用 Fastlog Mgorm 查询日志
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ProtoGenOpts) Reset() {
	*x = ProtoGenOpts{}
	mi := &file_easymicro_ext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoGenOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoGenOpts) ProtoMessage() {}

func (x *ProtoGenOpts) ProtoReflect() protoreflect.Message {
	mi := &file_easymicro_ext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoGenOpts.ProtoReflect.Descriptor instead.
func (*ProtoGenOpts) Descriptor() ([]byte, []int) {
	return file_easymicro_ext_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoGenOpts) GetServerPackage() string {
	if x != nil {
		return x.ServerPackage
	}
	return ""
}

func (x *ProtoGenOpts) GetDisabledLoadFastlog() bool {
	if x != nil {
		return x.DisabledLoadFastlog
	}
	return false
}

func (x *ProtoGenOpts) GetDisabledLoadMongo() bool {
	if x != nil {
		return x.DisabledLoadMongo
	}
	return false
}

func (x *ProtoGenOpts) GetDisabledLoadRedis() bool {
	if x != nil {
		return x.DisabledLoadRedis
	}
	return false
}

func (x *ProtoGenOpts) GetDisabledLoadEtcd() bool {
	if x != nil {
		return x.DisabledLoadEtcd
	}
	return false
}

func (x *ProtoGenOpts) GetDisabledLoadDiscovery() bool {
	if x != nil {
		return x.DisabledLoadDiscovery
	}
	return false
}

func (x *ProtoGenOpts) GetDisabledLoadNats() bool {
	if x != nil {
		return x.DisabledLoadNats
	}
	return false
}

func (x *ProtoGenOpts) GetDisabledElect() bool {
	if x != nil {
		return x.DisabledElect
	}
	return false
}

func (x *ProtoGenOpts) GetElectDriverName() string {
	if x != nil {
		return x.ElectDriverName
	}
	return ""
}

func (x *ProtoGenOpts) GetElectDriverConn() string {
	if x != nil {
		return x.ElectDriverConn
	}
	return ""
}

func (x *ProtoGenOpts) GetGrpcSchema() string {
	if x != nil {
		return x.GrpcSchema
	}
	return ""
}

func (x *ProtoGenOpts) GetDiscoveryName() string {
	if x != nil {
		return x.DiscoveryName
	}
	return ""
}

func (x *ProtoGenOpts) GetEnabledHealth() bool {
	if x != nil {
		return x.EnabledHealth
	}
	return false
}

func (x *ProtoGenOpts) GetAutoGoModClient() bool {
	if x != nil {
		return x.AutoGoModClient
	}
	return false
}

func (x *ProtoGenOpts) GetAutoGoModServer() bool {
	if x != nil {
		return x.AutoGoModServer
	}
	return false
}

func (x *ProtoGenOpts) GetMgormRedisCacheConn() string {
	if x != nil {
		return x.MgormRedisCacheConn
	}
	return ""
}

func (x *ProtoGenOpts) GetDisabledMgormRedisCacheConn() bool {
	if x != nil {
		return x.DisabledMgormRedisCacheConn
	}
	return false
}

func (x *ProtoGenOpts) GetDisabledFastlogMgormQuery() bool {
	if x != nil {
		return x.DisabledFastlogMgormQuery
	}
	return false
}

var file_easymicro_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*ErrMessage)(nil),
		Field:         66001,
		Name:          "easymicro_ext.err_message",
		Tag:           "bytes,66001,opt,name=err_message",
		Filename:      "easymicro_ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*ProtoGenOpts)(nil),
		Field:         66001,
		Name:          "easymicro_ext.proto_gen_opts",
		Tag:           "bytes,66001,opt,name=proto_gen_opts",
		Filename:      "easymicro_ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*JsonSchemaOutputOpts)(nil),
		Field:         66001,
		Name:          "easymicro_ext.json_schema_output_opts",
		Tag:           "bytes,66001,opt,name=json_schema_output_opts",
		Filename:      "easymicro_ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*JobOpts)(nil),
		Field:         66001,
		Name:          "easymicro_ext.job_opts",
		Tag:           "bytes,66001,opt,name=job_opts",
		Filename:      "easymicro_ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         66001,
		Name:          "easymicro_ext.is_rpc_port",
		Tag:           "varint,66001,opt,name=is_rpc_port",
		Filename:      "easymicro_ext.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional easymicro_ext.ErrMessage err_message = 66001;
	E_ErrMessage = &file_easymicro_ext_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional easymicro_ext.ProtoGenOpts proto_gen_opts = 66001;
	E_ProtoGenOpts = &file_easymicro_ext_proto_extTypes[1] // 代码自动生成的扩展
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional easymicro_ext.JsonSchemaOutputOpts json_schema_output_opts = 66001;
	E_JsonSchemaOutputOpts = &file_easymicro_ext_proto_extTypes[2]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional easymicro_ext.JobOpts job_opts = 66001;
	E_JobOpts = &file_easymicro_ext_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional bool is_rpc_port = 66001;
	E_IsRpcPort = &file_easymicro_ext_proto_extTypes[4] // 用于在proto中指定和维护服务的rpc 端口
)

var File_easymicro_ext_proto protoreflect.FileDescriptor

const file_easymicro_ext_proto_rawDesc = "" +
	"\n" +
	"\x13easymicro_ext.proto\x12\reasymicro_ext\x1a google/protobuf/descriptor.proto\"&\n" +
	"\n" +
	"ErrMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\t\n" +
	"\aJobOpts\"\x82\x02\n" +
	"\x14JsonSchemaOutputOpts\x12+\n" +
	"\x11enabled_reference\x18\x01 \x01(\bR\x10enabledReference\x12D\n" +
	"\x1edisabled_additional_properties\x18\x02 \x01(\bR\x1cdisabledAdditionalProperties\x12Q\n" +
	"&disabled_require_from_json_schema_tags\x18\x03 \x01(\bR!disabledRequireFromJsonSchemaTags\x12$\n" +
	"\x0efield_name_tag\x18\x04 \x01(\tR\ffieldNameTag\"\xe1\x06\n" +
	"\fProtoGenOpts\x12%\n" +
	"\x0eserver_package\x18\x01 \x01(\tR\rserverPackage\x122\n" +
	"\x15disabled_load_fastlog\x18\x02 \x01(\bR\x13disabledLoadFastlog\x12.\n" +
	"\x13disabled_load_mongo\x18\x03 \x01(\bR\x11disabledLoadMongo\x12.\n" +
	"\x13disabled_load_redis\x18\x04 \x01(\bR\x11disabledLoadRedis\x12,\n" +
	"\x12disabled_load_etcd\x18\x05 \x01(\bR\x10disabledLoadEtcd\x126\n" +
	"\x17disabled_load_discovery\x18\x06 \x01(\bR\x15disabledLoadDiscovery\x12,\n" +
	"\x12disabled_load_nats\x18\a \x01(\bR\x10disabledLoadNats\x12%\n" +
	"\x0edisabled_elect\x18\b \x01(\bR\rdisabledElect\x12*\n" +
	"\x11elect_driver_name\x18\t \x01(\tR\x0felectDriverName\x12*\n" +
	"\x11elect_driver_conn\x18\n" +
	" \x01(\tR\x0felectDriverConn\x12\x1f\n" +
	"\vgrpc_schema\x18\v \x01(\tR\n" +
	"grpcSchema\x12%\n" +
	"\x0ediscovery_name\x18\f \x01(\tR\rdiscoveryName\x12%\n" +
	"\x0eenabled_health\x18\r \x01(\bR\renabledHealth\x12+\n" +
	"\x12auto_go_mod_client\x18\x0e \x01(\bR\x0fautoGoModClient\x12+\n" +
	"\x12auto_go_mod_server\x18\x0f \x01(\bR\x0fautoGoModServer\x123\n" +
	"\x16mgorm_redis_cache_conn\x18\x10 \x01(\tR\x13mgormRedisCacheConn\x12D\n" +
	"\x1fdisabled_mgorm_redis_cache_conn\x18\x11 \x01(\bR\x1bdisabledMgormRedisCacheConn\x12?\n" +
	"\x1cdisabled_fastlog_mgorm_query\x18\x12 \x01(\bR\x19disabledFastlogMgormQuery:_\n" +
	"\verr_message\x12!.google.protobuf.EnumValueOptions\x18у\x04 \x01(\v2\x19.easymicro_ext.ErrMessageR\n" +
	"errMessage:a\n" +
	"\x0eproto_gen_opts\x12\x1c.google.protobuf.FileOptions\x18у\x04 \x01(\v2\x1b.easymicro_ext.ProtoGenOptsR\fprotoGenOpts:}\n" +
	"\x17json_schema_output_opts\x12\x1f.google.protobuf.MessageOptions\x18у\x04 \x01(\v2#.easymicro_ext.JsonSchemaOutputOptsR\x14jsonSchemaOutputOpts:S\n" +
	"\bjob_opts\x12\x1e.google.protobuf.MethodOptions\x18у\x04 \x01(\v2\x16.easymicro_ext.JobOptsR\ajobOpts:>\n" +
	"\vis_rpc_port\x12\x1c.google.protobuf.EnumOptions\x18у\x04 \x01(\bR\tisRpcPortB#Z!github.com/995933447/easymicro/pbb\x06proto3"

var (
	file_easymicro_ext_proto_rawDescOnce sync.Once
	file_easymicro_ext_proto_rawDescData []byte
)

func file_easymicro_ext_proto_rawDescGZIP() []byte {
	file_easymicro_ext_proto_rawDescOnce.Do(func() {
		file_easymicro_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_easymicro_ext_proto_rawDesc), len(file_easymicro_ext_proto_rawDesc)))
	})
	return file_easymicro_ext_proto_rawDescData
}

var file_easymicro_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_easymicro_ext_proto_goTypes = []any{
	(*ErrMessage)(nil),                    // 0: easymicro_ext.ErrMessage
	(*JobOpts)(nil),                       // 1: easymicro_ext.JobOpts
	(*JsonSchemaOutputOpts)(nil),          // 2: easymicro_ext.JsonSchemaOutputOpts
	(*ProtoGenOpts)(nil),                  // 3: easymicro_ext.ProtoGenOpts
	(*descriptorpb.EnumValueOptions)(nil), // 4: google.protobuf.EnumValueOptions
	(*descriptorpb.FileOptions)(nil),      // 5: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 6: google.protobuf.MessageOptions
	(*descriptorpb.MethodOptions)(nil),    // 7: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),      // 8: google.protobuf.EnumOptions
}
var file_easymicro_ext_proto_depIdxs = []int32{
	4, // 0: easymicro_ext.err_message:extendee -> google.protobuf.EnumValueOptions
	5, // 1: easymicro_ext.proto_gen_opts:extendee -> google.protobuf.FileOptions
	6, // 2: easymicro_ext.json_schema_output_opts:extendee -> google.protobuf.MessageOptions
	7, // 3: easymicro_ext.job_opts:extendee -> google.protobuf.MethodOptions
	8, // 4: easymicro_ext.is_rpc_port:extendee -> google.protobuf.EnumOptions
	0, // 5: easymicro_ext.err_message:type_name -> easymicro_ext.ErrMessage
	3, // 6: easymicro_ext.proto_gen_opts:type_name -> easymicro_ext.ProtoGenOpts
	2, // 7: easymicro_ext.json_schema_output_opts:type_name -> easymicro_ext.JsonSchemaOutputOpts
	1, // 8: easymicro_ext.job_opts:type_name -> easymicro_ext.JobOpts
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	5, // [5:9] is the sub-list for extension type_name
	0, // [0:5] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_easymicro_ext_proto_init() }
func file_easymicro_ext_proto_init() {
	if File_easymicro_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_easymicro_ext_proto_rawDesc), len(file_easymicro_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_easymicro_ext_proto_goTypes,
		DependencyIndexes: file_easymicro_ext_proto_depIdxs,
		MessageInfos:      file_easymicro_ext_proto_msgTypes,
		ExtensionInfos:    file_easymicro_ext_proto_extTypes,
	}.Build()
	File_easymicro_ext_proto = out.File
	file_easymicro_ext_proto_goTypes = nil
	file_easymicro_ext_proto_depIdxs = nil
}
