package main

var rpcFileHeadTemplate = `// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package {{.ServiceNamespace}}

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	{{- if .ShouldImportContext }}
	"context"
	{{- end }}
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema = "{{.ResolveSchema}}"
	EasymicroDiscoveryName = "{{.DiscoveryName}}"
)
`

var rpcFileDefineServiceTemplate = `
const EasymicroGRPCPbServiceName{{.ServiceName}} = "{{.ServiceNamespace}}.{{.ServiceName}}"

var {{.ServiceNameLowerCamel}}Default = &{{.ServiceName}}{}

func {{.ServiceName}}GRPC() *{{.ServiceName}} {
	return {{.ServiceNameLowerCamel}}Default
}

func New{{.ServiceName}}GRPC(dialOpts ...grpc.DialOption) *{{.ServiceName}} {
	return &{{.ServiceName}}{
		dialOpts: dialOpts,
	}
}

type {{.ServiceName}} struct {
	c        {{.ServiceName}}Client
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *{{.ServiceName}}) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *{{.ServiceName}}) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceName{{.ServiceName}})
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceName{{.ServiceName}}, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = New{{.ServiceName}}Client(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

`

var rpcFileServiceUnaryMethodTemplate = `
func (s *{{.ServiceName}}) {{.MethodName}}(ctx context.Context, in *{{.Req}}, opts ...grpc.CallOption) (*{{.Resp}}, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.{{.MethodName}}(ctx, in, opts...)
}

`

var rpcFileServiceServerStreamMethodTemplate = `
func (s *{{.ServiceName}}) {{.MethodName}}(ctx context.Context, in *{{.Req}}, opts ...grpc.CallOption) (grpc.ServerStreamingClient[{{.Resp}}], error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}
	return s.c.{{.MethodName}}(ctx, in, opts...)
}

`

var rpcFileServiceClientStreamMethodTemplate = `
func (s *{{.ServiceName}}) {{.MethodName}}(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[{{.Req}}, {{.Resp}}], error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}
	return s.c.{{.MethodName}}(ctx, opts...)
}

`

var rpcFileServiceBothStreamMethodTemplate = `
func (s *{{.ServiceName}}) {{.MethodName}}(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[{{.Req}}, {{.Resp}}], error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}
	return s.c.{{.MethodName}}(ctx, opts...)
}

`
